# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Mnc Livestock Report
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_null_geometry as drop_null_geometry,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_mnc.tasks import add_totals_row as add_totals_row
from ecoscope_workflows_ext_mnc.tasks import convert_to_int as convert_to_int
from ecoscope_workflows_ext_mnc.tasks import (
    create_gdf_from_dict as create_gdf_from_dict,
)
from ecoscope_workflows_ext_mnc.tasks import (
    exclude_geom_outliers as exclude_geom_outliers,
)
from ecoscope_workflows_ext_mnc.tasks import filter_columns as filter_columns
from ecoscope_workflows_ext_mnc.tasks import map_column_values as map_column_values
from ecoscope_workflows_ext_mnc.tasks import (
    replace_missing_with_label as replace_missing_with_label,
)
from ecoscope_workflows_ext_mnc.tasks import to_sentence_case as to_sentence_case
from ecoscope_workflows_ext_mnc.tasks import transform_columns as transform_columns
from ecoscope_workflows_ext_ste.tasks import (
    annotate_gdf_dict_with_geom_type as annotate_gdf_dict_with_geom_type,
)
from ecoscope_workflows_ext_ste.tasks import (
    combine_deckgl_map_layers as combine_deckgl_map_layers,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_custom_text_layer as create_custom_text_layer,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layer_from_gdf as create_deckgl_layer_from_gdf,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layers_from_gdf_dict as create_deckgl_layers_from_gdf_dict,
)
from ecoscope_workflows_ext_ste.tasks import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from ecoscope_workflows_ext_ste.tasks import get_gdf_geom_type as get_gdf_geom_type
from ecoscope_workflows_ext_ste.tasks import split_gdf_by_column as split_gdf_by_column
from ecoscope_workflows_ext_ste.tasks import view_state_deck_gdf as view_state_deck_gdf

# %% [markdown]
# ## Set workflow details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
    time_format=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .partial(**time_range_params)
    .call()
)


# %% [markdown]
# ## Set groupers

# %%
# parameters

groupers_params = dict()

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .partial(groupers=[], **groupers_params)
    .call()
)


# %% [markdown]
# ## Connect to ER

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.set_task_instance_id("er_client_name")
    .handle_errors()
    .with_tracing()
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ## Configure base map layers

# %%
# parameters

configure_base_maps_params = dict()

# %%
# call the task


configure_base_maps = (
    set_base_maps_pydeck.set_task_instance_id("configure_base_maps")
    .handle_errors()
    .with_tracing()
    .partial(
        base_maps=[
            {
                "url": "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
                "opacity": 1,
                "max_zoom": 20,
            }
        ],
        **configure_base_maps_params,
    )
    .call()
)


# %% [markdown]
# ## Download MNC community conservancy boundaries

# %%
# parameters

persist_mnc_gpkg_params = dict()

# %%
# call the task


persist_mnc_gpkg = (
    fetch_and_persist_file.set_task_instance_id("persist_mnc_gpkg")
    .handle_errors()
    .with_tracing()
    .partial(
        url="https://www.dropbox.com/scl/fi/14rcy4lkwp7xgewj3xf7k/mnc_conservancy.gpkg?rlkey=mtqo7ivxrnvjonm2z1zez6h6f&st=gtdi4vv0&dl=0",
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        overwrite_existing=False,
        retries=3,
        unzip=False,
        **persist_mnc_gpkg_params,
    )
    .call()
)


# %% [markdown]
# ## Download MNC Parcels gpkg

# %%
# parameters

download_mnc_parcels_params = dict()

# %%
# call the task


download_mnc_parcels = (
    fetch_and_persist_file.set_task_instance_id("download_mnc_parcels")
    .handle_errors()
    .with_tracing()
    .partial(
        url="https://www.dropbox.com/scl/fi/33rdzy896rh91gtkfs2j3/mnc_across_the_river_parcels.gpkg?rlkey=xima1v0rozc0h9h78esfogx6q&st=o3gkk5p1&dl=0",
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        overwrite_existing=False,
        retries=3,
        unzip=False,
        **download_mnc_parcels_params,
    )
    .call()
)


# %% [markdown]
# ## Load community conservancy boundaries

# %%
# parameters

load_comm_shp_params = dict()

# %%
# call the task


load_comm_shp = (
    load_df.set_task_instance_id("load_comm_shp")
    .handle_errors()
    .with_tracing()
    .partial(
        file_path=persist_mnc_gpkg,
        layer=None,
        deserialize_json=False,
        **load_comm_shp_params,
    )
    .call()
)


# %% [markdown]
# ## Split loaded gdf by various grazing zones and blocks

# %%
# parameters

split_gdf_by_zone_params = dict()

# %%
# call the task


split_gdf_by_zone = (
    split_gdf_by_column.set_task_instance_id("split_gdf_by_zone")
    .handle_errors()
    .with_tracing()
    .partial(gdf=load_comm_shp, column="grazing_zone", **split_gdf_by_zone_params)
    .call()
)


# %% [markdown]
# ## Annotate community conservancy gpkg with geom type

# %%
# parameters

annotate_comm_gdf_dict_params = dict()

# %%
# call the task


annotate_comm_gdf_dict = (
    annotate_gdf_dict_with_geom_type.set_task_instance_id("annotate_comm_gdf_dict")
    .handle_errors()
    .with_tracing()
    .partial(gdf_dict=split_gdf_by_zone, **annotate_comm_gdf_dict_params)
    .call()
)


# %% [markdown]
# ## Create styled layers from split mnc zones

# %%
# parameters

create_mnc_styled_layers_params = dict()

# %%
# call the task


create_mnc_styled_layers = (
    create_deckgl_layers_from_gdf_dict.set_task_instance_id("create_mnc_styled_layers")
    .handle_errors()
    .with_tracing()
    .partial(
        gdf_dict=annotate_comm_gdf_dict,
        styles={
            "Conservancy": {
                "extruded": False,
                "get_fill_color": [169, 169, 169],
                "get_line_color": [169, 169, 169],
                "get_line_width": 4.0,
                "stroked": True,
                "filled": False,
                "opacity": 0.95,
            },
            "Conservancy Herd Zone": {
                "extruded": False,
                "get_fill_color": [173, 255, 47],
                "get_line_color": [173, 255, 47],
                "get_line_width": 1.95,
                "stroked": True,
                "filled": True,
                "opacity": 0.15,
            },
            "Grazing Zone 1": {
                "extruded": False,
                "get_fill_color": [85, 107, 47],
                "get_line_color": [85, 107, 47],
                "get_line_width": 1.95,
                "stroked": True,
                "filled": True,
                "opacity": 0.15,
            },
            "Grazing Zone 2": {
                "extruded": False,
                "get_fill_color": [0, 139, 139],
                "get_line_color": [0, 139, 139],
                "get_line_width": 1.95,
                "stroked": True,
                "filled": True,
                "opacity": 0.15,
            },
            "Grazing Zone 3": {
                "extruded": False,
                "get_fill_color": [0, 100, 0],
                "get_line_color": [0, 100, 0],
                "get_line_width": 1.95,
                "stroked": True,
                "filled": True,
                "opacity": 0.15,
            },
            "Grazing Zone 4": {
                "extruded": False,
                "get_fill_color": [143, 188, 139],
                "get_line_color": [143, 188, 139],
                "get_line_width": 1.95,
                "stroked": True,
                "filled": True,
                "opacity": 0.15,
            },
        },
        legends={
            "title": "Legend",
            "values": [
                {"label": "Conservancy", "color": "#a9a9a9"},
                {"label": "Conservancy Herd Zone", "color": "#adff2f"},
                {"label": "Grazing Zone 1", "color": "#556b2f"},
                {"label": "Grazing Zone 2", "color": "#008b8b"},
                {"label": "Grazing Zone 3", "color": "#006400"},
                {"label": "Grazing Zone 4", "color": "#8fbc8b"},
            ],
        },
        **create_mnc_styled_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Create conservancy boundaries

# %%
# parameters

create_conservancy_boundaries_params = dict()

# %%
# call the task


create_conservancy_boundaries = (
    create_deckgl_layers_from_gdf_dict.set_task_instance_id(
        "create_conservancy_boundaries"
    )
    .handle_errors()
    .with_tracing()
    .partial(
        gdf_dict=annotate_comm_gdf_dict,
        styles={
            "Conservancy": {
                "extruded": False,
                "get_fill_color": [169, 169, 169],
                "get_line_color": [169, 169, 169],
                "get_line_width": 4.0,
                "stroked": True,
                "filled": False,
                "opacity": 0.95,
            }
        },
        legends={
            "title": "Legend",
            "values": [{"label": "Boundaries", "color": "#a9a9a9"}],
        },
        **create_conservancy_boundaries_params,
    )
    .call()
)


# %% [markdown]
# ## Create conservancy gdf from split dict

# %%
# parameters

conservancy_gdf_params = dict()

# %%
# call the task


conservancy_gdf = (
    create_gdf_from_dict.set_task_instance_id("conservancy_gdf")
    .handle_errors()
    .with_tracing()
    .partial(gdf_dict=split_gdf_by_zone, key="Conservancy", **conservancy_gdf_params)
    .call()
)


# %% [markdown]
# ## Create group ranch gdf from loaded gdf

# %%
# parameters

overall_grazing_zones_params = dict()

# %%
# call the task


overall_grazing_zones = (
    filter_df.set_task_instance_id("overall_grazing_zones")
    .handle_errors()
    .with_tracing()
    .partial(
        column_name="grazing_zone",
        op="ne",
        value="Conservancy",
        df=load_comm_shp,
        reset_index=False,
        **overall_grazing_zones_params,
    )
    .call()
)


# %% [markdown]
# ## Create conservancy text layers here

# %%
# parameters

conservancy_text_layer_params = dict()

# %%
# call the task


conservancy_text_layer = (
    create_custom_text_layer.set_task_instance_id("conservancy_text_layer")
    .handle_errors()
    .with_tracing()
    .partial(
        geodataframe=conservancy_gdf,
        layer_style={
            "get_text": "name",
            "get_color": [0, 0, 0, 255],
            "get_size": 1500,
            "size_units": "meters",
            "size_min_pixels": 70,
            "size_max_pixels": 100,
            "size_scale": 2.25,
            "font_family": "Calibri",
            "font_weight": "700",
            "get_text_anchor": "middle",
            "get_alignment_baseline": "center",
            "billboard": True,
            "background_padding": [4, 8],
            "pickable": True,
            "auto_highlight": False,
        },
        use_centroid=True,
        legend=None,
        **conservancy_text_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Load mnc parcels

# %%
# parameters

load_mnc_parcels_params = dict()

# %%
# call the task


load_mnc_parcels = (
    load_df.set_task_instance_id("load_mnc_parcels")
    .handle_errors()
    .with_tracing()
    .partial(
        file_path=download_mnc_parcels,
        layer=None,
        deserialize_json=False,
        **load_mnc_parcels_params,
    )
    .call()
)


# %% [markdown]
# ## Assign geom type to mnc parcels

# %%
# parameters

assign_mnc_geom_params = dict()

# %%
# call the task


assign_mnc_geom = (
    get_gdf_geom_type.set_task_instance_id("assign_mnc_geom")
    .handle_errors()
    .with_tracing()
    .partial(gdf=load_mnc_parcels, **assign_mnc_geom_params)
    .call()
)


# %% [markdown]
# ## Create mnc parcels layers

# %%
# parameters

create_mnc_parcels_layers_params = dict()

# %%
# call the task


create_mnc_parcels_layers = (
    create_deckgl_layer_from_gdf.set_task_instance_id("create_mnc_parcels_layers")
    .handle_errors()
    .with_tracing()
    .partial(
        gdf=assign_mnc_geom,
        style={
            "extruded": False,
            "get_fill_color": [189, 183, 107],
            "get_line_color": [189, 183, 107],
            "get_line_width": 1.95,
            "stroked": True,
            "filled": True,
            "opacity": 0.15,
        },
        legend={"title": "", "values": [{"label": "Parcels", "color": "#bdb76b"}]},
        **create_mnc_parcels_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Retrieve all events

# %%
# parameters

get_events_data_params = dict()

# %%
# call the task


get_events_data = (
    get_events.set_task_instance_id("get_events_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client_name,
        time_range=time_range,
        event_columns=[
            "id",
            "time",
            "event_type",
            "event_category",
            "reported_by",
            "serial_number",
            "geometry",
            "created_at",
            "event_details",
            "patrols",
        ],
        event_types=[],
        raise_on_empty=True,
        include_details=True,
        include_updates=False,
        include_related_events=False,
        include_null_geometry=False,
        include_display_values=False,
        **get_events_data_params,
    )
    .call()
)


# %% [markdown]
# ## Extract date from events data

# %%
# parameters

extract_event_date_params = dict()

# %%
# call the task


extract_event_date = (
    extract_column_as_type.set_task_instance_id("extract_event_date")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=get_events_data,
        column_name="time",
        output_type="date",
        output_column_name="date",
        **extract_event_date_params,
    )
    .call()
)


# %% [markdown]
# ## Add temporal index on events

# %%
# parameters

events_temporal_params = dict()

# %%
# call the task


events_temporal = (
    add_temporal_index.set_task_instance_id("events_temporal")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_event_date,
        time_col="date",
        groupers=groupers,
        cast_to_datetime=True,
        format="mixed",
        **events_temporal_params,
    )
    .call()
)


# %% [markdown]
# ## Retrieve mobile_boma_rep

# %%
# parameters

filter_mobile_boma_params = dict()

# %%
# call the task


filter_mobile_boma = (
    filter_df.set_task_instance_id("filter_mobile_boma")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="event_type",
        op="equal",
        value="mobile_boma_rep",
        df=events_temporal,
        reset_index=False,
        **filter_mobile_boma_params,
    )
    .call()
)


# %% [markdown]
# ## Retrieve cattle_count

# %%
# parameters

filter_cattle_count_params = dict()

# %%
# call the task


filter_cattle_count = (
    filter_df.set_task_instance_id("filter_cattle_count")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="event_type",
        op="equal",
        value="cattle_count",
        df=events_temporal,
        reset_index=False,
        **filter_cattle_count_params,
    )
    .call()
)


# %% [markdown]
# ## Normalize event details columns

# %%
# parameters

normalize_mb_values_params = dict()

# %%
# call the task


normalize_mb_values = (
    normalize_json_column.set_task_instance_id("normalize_mb_values")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column="event_details",
        df=filter_mobile_boma,
        skip_if_not_exists=True,
        sort_columns=True,
        **normalize_mb_values_params,
    )
    .call()
)


# %% [markdown]
# ## Normalize event details columns

# %%
# parameters

normalize_cc_values_params = dict()

# %%
# call the task


normalize_cc_values = (
    normalize_json_column.set_task_instance_id("normalize_cc_values")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column="event_details",
        df=filter_cattle_count,
        skip_if_not_exists=True,
        sort_columns=True,
        **normalize_cc_values_params,
    )
    .call()
)


# %% [markdown]
# ## Rename mobile boma columns

# %%
# parameters

rename_mobile_boma_params = dict()

# %%
# call the task


rename_mobile_boma = (
    transform_columns.set_task_instance_id("rename_mobile_boma")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        drop_columns=[],
        retain_columns=[],
        rename_columns={"event_details__mobile_boma": "boma"},
        skip_missing_rename=True,
        required_columns=["event_details__mobile_boma"],
        df=normalize_mb_values,
        **rename_mobile_boma_params,
    )
    .call()
)


# %% [markdown]
# ## Rename cattle count columns

# %%
# parameters

rename_cattle_count_params = dict()

# %%
# call the task


rename_cattle_count = (
    transform_columns.set_task_instance_id("rename_cattle_count")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "event_details__cattle_in_zone_4": "zone_4",
            "event_details__cattle_in_zone_1_outside_mobile_boma": "zone_1",
            "event_details__cattle_in_zone_23_outside_mobile_boma": "zone_2_3",
            "event_details__total_cattle_counted_from_all_zones": "total_count",
        },
        skip_missing_rename=True,
        required_columns=["event_details__total_cattle_counted_from_all_zones"],
        df=normalize_cc_values,
        **rename_cattle_count_params,
    )
    .call()
)


# %% [markdown]
# ## Rename mobile_boma_rep value to Mobile Boma

# %%
# parameters

rename_boma_values_params = dict()

# %%
# call the task


rename_boma_values = (
    map_column_values.set_task_instance_id("rename_boma_values")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=rename_mobile_boma,
        columns=["event_type"],
        value_map={"mobile_boma_rep": "Mobile boma"},
        inplace=False,
        **rename_boma_values_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate total boma counts

# %%
# parameters

calculate_total_boma_params = dict()

# %%
# call the task


calculate_total_boma = (
    summarize_df.set_task_instance_id("calculate_total_boma")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        groupby_cols=["date"],
        summary_params=[
            {"display_name": "total_count", "aggregator": "nunique", "column": "id"}
        ],
        reset_index=True,
        df=rename_boma_values,
        **calculate_total_boma_params,
    )
    .call()
)


# %% [markdown]
# ## Add total row on total boma counts

# %%
# parameters

add_total_boma_row_params = dict()

# %%
# call the task


add_total_boma_row = (
    add_totals_row.set_task_instance_id("add_total_boma_row")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        label_col=["date"],
        label="Total",
        df=calculate_total_boma,
        **add_total_boma_row_params,
    )
    .call()
)


# %% [markdown]
# ## Persist total boma count df

# %%
# parameters

persist_boma_count_df_params = dict()

# %%
# call the task


persist_boma_count_df = (
    persist_df.set_task_instance_id("persist_boma_count_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        df=add_total_boma_row,
        filename="total_boma_count_by_date",
        **persist_boma_count_df_params,
    )
    .call()
)


# %% [markdown]
# ## Cattle count summary table

# %%
# parameters

filter_cattle_cols_params = dict()

# %%
# call the task


filter_cattle_cols = (
    filter_columns.set_task_instance_id("filter_cattle_cols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=rename_cattle_count,
        columns=["date", "zone_1", "zone_2_3", "zone_4", "total_count"],
        exclude=[],
        **filter_cattle_cols_params,
    )
    .call()
)


# %% [markdown]
# ## Persist cattle count summary table

# %%
# parameters

persist_cattle_count_df_params = dict()

# %%
# call the task


persist_cattle_count_df = (
    persist_df.set_task_instance_id("persist_cattle_count_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        filename="mobile_boma_summary_table",
        df=filter_cattle_cols,
        **persist_cattle_count_df_params,
    )
    .call()
)


# %% [markdown]
# ## Exclude geom outliers from mobile_boma_rep events

# %%
# parameters

exclude_mb_outliers_params = dict()

# %%
# call the task


exclude_mb_outliers = (
    exclude_geom_outliers.set_task_instance_id("exclude_mb_outliers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=rename_boma_values, z_threshold=3, **exclude_mb_outliers_params)
    .call()
)


# %% [markdown]
# ## Remove mobile boma invalid points

# %%
# parameters

remove_mb_invalid_geoms_params = dict()

# %%
# call the task


remove_mb_invalid_geoms = (
    drop_null_geometry.set_task_instance_id("remove_mb_invalid_geoms")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        gdf=exclude_mb_outliers,
        geometry_column="geometry",
        **remove_mb_invalid_geoms_params,
    )
    .call()
)


# %% [markdown]
# ## Apply Colormap to mobile boma events

# %%
# parameters

apply_mb_colormap_params = dict()

# %%
# call the task


apply_mb_colormap = (
    apply_color_map.set_task_instance_id("apply_mb_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        input_column_name="event_type",
        output_column_name="event_type_colors",
        colormap="tab20",
        df=remove_mb_invalid_geoms,
        **apply_mb_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Generate mobile boma point layers

# %%
# parameters

generate_mb_layers_params = dict()

# %%
# call the task


generate_mb_layers = (
    create_scatterplot_layer.set_task_instance_id("generate_mb_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={
            "get_fill_color": "event_type_colors",
            "get_line_color": "event_type_colors",
            "get_radius": 4,
            "opacity": 0.75,
            "stroked": True,
        },
        legend={
            "title": "Boma Movements",
            "label_column": "event_type",
            "color_column": "event_type_colors",
            "sort": "ascending",
            "label_suffix": None,
        },
        geodataframe=apply_mb_colormap,
        **generate_mb_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Global map zoom value

# %%
# parameters

global_zoom_value_params = dict()

# %%
# call the task


global_zoom_value = (
    view_state_deck_gdf.set_task_instance_id("global_zoom_value")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(pitch=0, bearing=0, gdf=overall_grazing_zones, **global_zoom_value_params)
    .call()
)


# %% [markdown]
# ## Combine styled layers with mobile boma

# %%
# parameters

combine_custom_mobile_boma_params = dict()

# %%
# call the task


combine_custom_mobile_boma = (
    combine_deckgl_map_layers.set_task_instance_id("combine_custom_mobile_boma")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        static_layers=[
            create_mnc_styled_layers,
            create_mnc_parcels_layers,
            conservancy_text_layer,
        ],
        grouped_layers=generate_mb_layers,
        **combine_custom_mobile_boma_params,
    )
    .call()
)


# %% [markdown]
# ## Draw mobile boma events map

# %%
# parameters

draw_mb_map_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_mb_map = (
    draw_map.set_task_instance_id("draw_mb_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        tile_layers=configure_base_maps,
        static=False,
        title=None,
        max_zoom=10,
        legend_style={"placement": "bottom-right"},
        geo_layers=combine_custom_mobile_boma,
        view_state=global_zoom_value,
        **draw_mb_map_params,
    )
    .call()
)


# %% [markdown]
# ## Persist mobile boma map HTML paths

# %%
# parameters

persist_mobile_boma_urls_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_mobile_boma_urls = (
    persist_text.set_task_instance_id("persist_mobile_boma_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=draw_mb_map,
        filename="boma_movement_map.html",
        **persist_mobile_boma_urls_params,
    )
    .call()
)


# %% [markdown]
# ## Retrieve livestock_predation_rep events

# %%
# parameters

filter_predation_params = dict()

# %%
# call the task


filter_predation = (
    filter_df.set_task_instance_id("filter_predation")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="event_type",
        op="equal",
        value="livestock_predation_rep",
        df=events_temporal,
        reset_index=False,
        **filter_predation_params,
    )
    .call()
)


# %% [markdown]
# ## Normalize event details columns

# %%
# parameters

normalize_predation_values_params = dict()

# %%
# call the task


normalize_predation_values = (
    normalize_json_column.set_task_instance_id("normalize_predation_values")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column="event_details",
        df=filter_predation,
        skip_if_not_exists=True,
        sort_columns=True,
        **normalize_predation_values_params,
    )
    .call()
)


# %% [markdown]
# ## Rename livestock predation columns

# %%
# parameters

rename_livestock_predation_params = dict()

# %%
# call the task


rename_livestock_predation = (
    transform_columns.set_task_instance_id("rename_livestock_predation")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "event_details__livestockpredation_comments": "livestock_predation_comments",
            "event_details__livestockpredation_location": "predation_location",
            "event_details__livestockpredation_causedeath": "predation_cause_of_death",
            "event_details__livestockpredation_retaliation": "predation_retaliation",
            "event_details__livestockpredation_supervision": "predation_supervision",
            "event_details__livestockpredation_predatorcount": "predator_count",
            "event_details__livestockpredation_killedjuvenile": "killed_juvenile",
            "event_details__livestockpredation_livestockowner": "livestock_owner",
            "event_details__livestockpredation_distancetopeople": "distance_to_people",
            "event_details__livestockpredation_livestockspecies": "livestock_species",
            "event_details__livestockpredation_livestockaffected": "livestock_affected",
            "event_details__livestockpredation_suspectedpredator": "suspected_predator",
            "event_details__livestockpredation_bomacontext": "boma_context",
            "event_details__livestockpredation_killedadultmale": "killed_adult_male",
            "event_details__livestockpredation_bomaconstruction": "boma_construction",
            "event_details__livestockpredation_woundedjuvenile": "wounded_juvenile",
            "event_details__livestockpredation_woundedadultfemale": "wounded_adult_female",
            "event_details__livestockpredation_woundedadultmale": "wounded_adult_male",
            "event_details__livestockpredation_bomaheight": "boma_height",
            "event_details__livestockpredation_bomavisibility": "boma_visibility",
        },
        skip_missing_rename=True,
        required_columns=[
            "event_details__livestockpredation_livestockaffected",
            "event_details__livestockpredation_livestockspecies",
            "event_details__livestockpredation_suspectedpredator",
        ],
        df=normalize_predation_values,
        **rename_livestock_predation_params,
    )
    .call()
)


# %% [markdown]
# ## Replace nulls on livestock predator table with unknown

# %%
# parameters

replace_livestock_nulls_params = dict()

# %%
# call the task


replace_livestock_nulls = (
    replace_missing_with_label.set_task_instance_id("replace_livestock_nulls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=rename_livestock_predation,
        columns=["suspected_predator", "livestock_species"],
        label="unknown",
        **replace_livestock_nulls_params,
    )
    .call()
)


# %% [markdown]
# ## Convert livestock_affected col to int

# %%
# parameters

convert_livestock_int_params = dict()

# %%
# call the task


convert_livestock_int = (
    convert_to_int.set_task_instance_id("convert_livestock_int")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=replace_livestock_nulls,
        columns=["livestock_affected"],
        errors="coerce",
        fill_value=0,
        inplace=False,
        **convert_livestock_int_params,
    )
    .call()
)


# %% [markdown]
# ## Capitalize columns in livestock predation

# %%
# parameters

livestock_preds_scase_params = dict()

# %%
# call the task


livestock_preds_scase = (
    to_sentence_case.set_task_instance_id("livestock_preds_scase")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=convert_livestock_int,
        columns=["suspected_predator", "livestock_species"],
        **livestock_preds_scase_params,
    )
    .call()
)


# %% [markdown]
# ## Persist livestock predation event details as gpkg

# %%
# parameters

persist_livestock_events_gpkg_params = dict()

# %%
# call the task


persist_livestock_events_gpkg = (
    persist_df.set_task_instance_id("persist_livestock_events_gpkg")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="gpkg",
        filename="livestock_predation_events",
        df=livestock_preds_scase,
        **persist_livestock_events_gpkg_params,
    )
    .call()
)


# %% [markdown]
# ## Persist livestock predation event details as csv

# %%
# parameters

persist_livestock_events_csv_params = dict()

# %%
# call the task


persist_livestock_events_csv = (
    persist_df.set_task_instance_id("persist_livestock_events_csv")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        filename="livestock_predation_events",
        df=livestock_preds_scase,
        **persist_livestock_events_csv_params,
    )
    .call()
)


# %% [markdown]
# ## Livestock predation summary table

# %%
# parameters

livestock_predation_summary_params = dict()

# %%
# call the task


livestock_predation_summary = (
    summarize_df.set_task_instance_id("livestock_predation_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        groupby_cols=["date", "suspected_predator", "livestock_species"],
        summary_params=[
            {
                "display_name": "no_affected",
                "aggregator": "sum",
                "column": "livestock_affected",
            }
        ],
        reset_index=True,
        df=livestock_preds_scase,
        **livestock_predation_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Persist livestock predation summary table

# %%
# parameters

persist_livestock_df_params = dict()

# %%
# call the task


persist_livestock_df = (
    persist_df.set_task_instance_id("persist_livestock_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        filename="livestock_predation_summary_table",
        df=livestock_predation_summary,
        **persist_livestock_df_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate livestock events recorded by date

# %%
# parameters

livestock_events_recorded_params = dict()

# %%
# call the task


livestock_events_recorded = (
    summarize_df.set_task_instance_id("livestock_events_recorded")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        groupby_cols=["date"],
        summary_params=[
            {"display_name": "no_of_events", "aggregator": "nunique", "column": "id"}
        ],
        reset_index=True,
        df=livestock_preds_scase,
        **livestock_events_recorded_params,
    )
    .call()
)


# %% [markdown]
# ## Add total row on livestock events recorded

# %%
# parameters

add_total_livestock_params = dict()

# %%
# call the task


add_total_livestock = (
    add_totals_row.set_task_instance_id("add_total_livestock")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        label_col=["date"],
        label="Total",
        df=livestock_events_recorded,
        **add_total_livestock_params,
    )
    .call()
)


# %% [markdown]
# ## Persist livestock events df

# %%
# parameters

livestock_events_df_params = dict()

# %%
# call the task


livestock_events_df = (
    persist_df.set_task_instance_id("livestock_events_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        df=add_total_livestock,
        filename="livestock_events_recorded_by_date",
        **livestock_events_df_params,
    )
    .call()
)


# %% [markdown]
# ## Exclude geom outliers from livestock predation events

# %%
# parameters

exclude_livestock_outliers_params = dict()

# %%
# call the task


exclude_livestock_outliers = (
    exclude_geom_outliers.set_task_instance_id("exclude_livestock_outliers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=livestock_preds_scase, z_threshold=3, **exclude_livestock_outliers_params
    )
    .call()
)


# %% [markdown]
# ## Remove invalid points from livestock predation events

# %%
# parameters

remove_livestock_invalid_geoms_params = dict()

# %%
# call the task


remove_livestock_invalid_geoms = (
    drop_null_geometry.set_task_instance_id("remove_livestock_invalid_geoms")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        gdf=exclude_livestock_outliers,
        geometry_column="geometry",
        **remove_livestock_invalid_geoms_params,
    )
    .call()
)


# %% [markdown]
# ## Apply Colormap to livestock predation events

# %%
# parameters

apply_livestock_colormap_params = dict()

# %%
# call the task


apply_livestock_colormap = (
    apply_color_map.set_task_instance_id("apply_livestock_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        input_column_name="livestock_species",
        output_column_name="colors",
        colormap="tab20",
        df=remove_livestock_invalid_geoms,
        **apply_livestock_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Generate livestock predation point layers

# %%
# parameters

generate_livestock_layers_params = dict()

# %%
# call the task


generate_livestock_layers = (
    create_scatterplot_layer.set_task_instance_id("generate_livestock_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={
            "get_fill_color": "colors",
            "get_line_color": "colors",
            "get_radius": 4,
            "opacity": 0.75,
            "stroked": True,
        },
        legend={
            "title": "Livestock Species",
            "label_column": "livestock_species",
            "color_column": "colors",
            "sort": "ascending",
            "label_suffix": None,
        },
        geodataframe=apply_livestock_colormap,
        **generate_livestock_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Combine styled layers with livestock predation events

# %%
# parameters

combine_custom_livestock_params = dict()

# %%
# call the task


combine_custom_livestock = (
    combine_deckgl_map_layers.set_task_instance_id("combine_custom_livestock")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        static_layers=[
            create_conservancy_boundaries,
            create_mnc_parcels_layers,
            conservancy_text_layer,
        ],
        grouped_layers=generate_livestock_layers,
        **combine_custom_livestock_params,
    )
    .call()
)


# %% [markdown]
# ## Draw livestock predation map

# %%
# parameters

draw_livestock_map_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_livestock_map = (
    draw_map.set_task_instance_id("draw_livestock_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        tile_layers=configure_base_maps,
        static=False,
        title=None,
        max_zoom=10,
        legend_style={"placement": "bottom-right"},
        geo_layers=combine_custom_livestock,
        view_state={
            "longitude": 35.2092935880001,
            "latitude": -1.257840580999955,
            "zoom": 9.75,
            "pitch": 0,
            "bearing": 0,
        },
        **draw_livestock_map_params,
    )
    .call()
)


# %% [markdown]
# ## Persist livestock predation map HTML paths

# %%
# parameters

persist_livestock_urls_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_livestock_urls = (
    persist_text.set_task_instance_id("persist_livestock_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=draw_livestock_map,
        filename="livestock_predation_events.html",
        **persist_livestock_urls_params,
    )
    .call()
)


# %% [markdown]
# ## Convert mobile boma map to png

# %%
# parameters

convert_mobile_boma_png_params = dict()

# %%
# call the task


convert_mobile_boma_png = (
    html_to_png.set_task_instance_id("convert_mobile_boma_png")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        html_path=persist_mobile_boma_urls,
        config={
            "full_page": False,
            "device_scale_factor": 2.0,
            "wait_for_timeout": 40000,
            "max_concurrent_pages": 1,
        },
        **convert_mobile_boma_png_params,
    )
    .call()
)


# %% [markdown]
# ## Convert livestock map to png

# %%
# parameters

convert_livestock_png_params = dict()

# %%
# call the task


convert_livestock_png = (
    html_to_png.set_task_instance_id("convert_livestock_png")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        html_path=persist_livestock_urls,
        config={
            "full_page": False,
            "device_scale_factor": 2.0,
            "wait_for_timeout": 40000,
            "max_concurrent_pages": 1,
        },
        **convert_livestock_png_params,
    )
    .call()
)


# %% [markdown]
# ## MNC event report dashboard

# %%
# parameters

mnc_events_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


mnc_events_dashboard = (
    gather_dashboard.set_task_instance_id("mnc_events_dashboard")
    .handle_errors()
    .with_tracing()
    .partial(
        details=workflow_details,
        widgets=[],
        time_range=time_range,
        groupers=groupers,
        **mnc_events_dashboard_params,
    )
    .call()
)
