# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_mnc.tasks import (
    create_gdf_from_dict as create_gdf_from_dict,
)
from ecoscope_workflows_ext_ste.tasks import (
    annotate_gdf_dict_with_geom_type as annotate_gdf_dict_with_geom_type_1,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_custom_text_layer as create_custom_text_layer,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layer_from_gdf as create_deckgl_layer_from_gdf,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layers_from_gdf_dict as create_deckgl_layers_from_gdf_dict,
)
from ecoscope_workflows_ext_ste.tasks import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from ecoscope_workflows_ext_ste.tasks import get_gdf_geom_type as get_gdf_geom_type_1
from ecoscope_workflows_ext_ste.tasks import split_gdf_by_column as split_gdf_by_column

get_events = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.transformation import (
    coerce_columns_to_int as coerce_columns_to_int,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    replace_empty_strings_in_columns as replace_empty_strings_in_columns,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_mnc.tasks import add_totals_row as add_totals_row
from ecoscope_workflows_ext_mnc.tasks import map_column_values as map_column_values
from ecoscope_workflows_ext_ste.tasks import (
    combine_deckgl_map_layers as combine_deckgl_map_layers,
)
from ecoscope_workflows_ext_ste.tasks import view_state_deck_gdf as view_state_deck_gdf

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("time_range") or {}))
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .partial(groupers=[], **(params_dict.get("groupers") or {}))
        .call()
    )

    er_client_name = (
        set_er_connection.validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    configure_base_maps = (
        set_base_maps_pydeck.validate()
        .set_task_instance_id("configure_base_maps")
        .handle_errors()
        .with_tracing()
        .partial(
            base_maps=[
                {
                    "url": "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
                    "opacity": 0.8,
                    "max_zoom": 20,
                },
                {
                    "url": "https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places_Alternate/MapServer/tile/{z}/{y}/{x}",
                    "opacity": 0.35,
                    "max_zoom": 20,
                },
            ],
            **(params_dict.get("configure_base_maps") or {}),
        )
        .call()
    )

    persist_mnc_gpkg = (
        fetch_and_persist_file.validate()
        .set_task_instance_id("persist_mnc_gpkg")
        .handle_errors()
        .with_tracing()
        .partial(
            url="https://www.dropbox.com/scl/fi/14rcy4lkwp7xgewj3xf7k/mnc_conservancy.gpkg?rlkey=mtqo7ivxrnvjonm2z1zez6h6f&st=gtdi4vv0&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params_dict.get("persist_mnc_gpkg") or {}),
        )
        .call()
    )

    download_mnc_parcels = (
        fetch_and_persist_file.validate()
        .set_task_instance_id("download_mnc_parcels")
        .handle_errors()
        .with_tracing()
        .partial(
            url="https://www.dropbox.com/scl/fi/33rdzy896rh91gtkfs2j3/mnc_across_the_river_parcels.gpkg?rlkey=xima1v0rozc0h9h78esfogx6q&st=o3gkk5p1&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params_dict.get("download_mnc_parcels") or {}),
        )
        .call()
    )

    load_comm_shp = (
        load_df.validate()
        .set_task_instance_id("load_comm_shp")
        .handle_errors()
        .with_tracing()
        .partial(
            file_path=persist_mnc_gpkg,
            layer=None,
            deserialize_json=False,
            **(params_dict.get("load_comm_shp") or {}),
        )
        .call()
    )

    split_gdf_by_zone = (
        split_gdf_by_column.validate()
        .set_task_instance_id("split_gdf_by_zone")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf=load_comm_shp,
            column="grazing_zone",
            **(params_dict.get("split_gdf_by_zone") or {}),
        )
        .call()
    )

    annotate_comm_gdf_dict = (
        annotate_gdf_dict_with_geom_type_1.validate()
        .set_task_instance_id("annotate_comm_gdf_dict")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf_dict=split_gdf_by_zone,
            **(params_dict.get("annotate_comm_gdf_dict") or {}),
        )
        .call()
    )

    create_mnc_styled_layers = (
        create_deckgl_layers_from_gdf_dict.validate()
        .set_task_instance_id("create_mnc_styled_layers")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf_dict=annotate_comm_gdf_dict,
            styles={
                "Conservancy": {
                    "extruded": False,
                    "get_fill_color": [119, 136, 153],
                    "get_line_color": [119, 136, 153],
                    "get_line_width": 1.55,
                    "stroked": True,
                    "filled": False,
                    "opacity": 0.7,
                },
                "Conservancy Herd Zone": {
                    "extruded": False,
                    "get_fill_color": [173, 255, 47],
                    "get_line_color": [173, 255, 47],
                    "get_line_width": 1.25,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.1,
                },
                "Grazing Zone 1": {
                    "extruded": False,
                    "get_fill_color": [85, 107, 47],
                    "get_line_color": [85, 107, 47],
                    "get_line_width": 1.25,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.1,
                },
                "Grazing Zone 2": {
                    "extruded": False,
                    "get_fill_color": [0, 139, 139],
                    "get_line_color": [0, 139, 139],
                    "get_line_width": 1.25,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.1,
                },
                "Grazing Zone 3": {
                    "extruded": False,
                    "get_fill_color": [0, 100, 0],
                    "get_line_color": [0, 100, 0],
                    "get_line_width": 1.25,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.1,
                },
                "Grazing Zone 4": {
                    "extruded": False,
                    "get_fill_color": [143, 188, 139],
                    "get_line_color": [143, 188, 139],
                    "get_line_width": 1.25,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.7,
                },
            },
            legends={
                "title": "Legend",
                "values": [
                    {"label": "Conservancy Boundaries", "color": "#778899"},
                    {"label": "Conservancy Herd Zone", "color": "#adff2f"},
                    {"label": "Grazing Zone 1", "color": "#556b2f"},
                    {"label": "Grazing Zone 2", "color": "#008b8b"},
                    {"label": "Grazing Zone 3", "color": "#006400"},
                    {"label": "Grazing Zone 4", "color": "#8fbc8b"},
                ],
            },
            **(params_dict.get("create_mnc_styled_layers") or {}),
        )
        .call()
    )

    create_conservancy_boundaries = (
        create_deckgl_layers_from_gdf_dict.validate()
        .set_task_instance_id("create_conservancy_boundaries")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf_dict=annotate_comm_gdf_dict,
            styles={
                "Conservancy": {
                    "extruded": False,
                    "get_fill_color": [119, 136, 153],
                    "get_line_color": [119, 136, 153],
                    "get_line_width": 1.55,
                    "stroked": True,
                    "filled": False,
                    "opacity": 0.7,
                }
            },
            legends={
                "title": "Legend",
                "values": [{"label": "Conservancy Boundaries", "color": "#778899"}],
            },
            **(params_dict.get("create_conservancy_boundaries") or {}),
        )
        .call()
    )

    conservancy_gdf = (
        create_gdf_from_dict.validate()
        .set_task_instance_id("conservancy_gdf")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf_dict=split_gdf_by_zone,
            key="Conservancy",
            **(params_dict.get("conservancy_gdf") or {}),
        )
        .call()
    )

    overall_grazing_zones = (
        filter_df.validate()
        .set_task_instance_id("overall_grazing_zones")
        .handle_errors()
        .with_tracing()
        .partial(
            column_name="grazing_zone",
            op="ne",
            value="Conservancy",
            df=load_comm_shp,
            reset_index=False,
            **(params_dict.get("overall_grazing_zones") or {}),
        )
        .call()
    )

    conservancy_text_layer = (
        create_custom_text_layer.validate()
        .set_task_instance_id("conservancy_text_layer")
        .handle_errors()
        .with_tracing()
        .partial(
            geodataframe=conservancy_gdf,
            layer_style={
                "get_text": "name",
                "get_color": [0, 0, 0, 255],
                "get_size": 1500,
                "size_units": "meters",
                "size_min_pixels": 70,
                "size_max_pixels": 100,
                "size_scale": 2.25,
                "font_family": "Calibri",
                "font_weight": "normal",
                "get_text_anchor": "middle",
                "get_alignment_baseline": "center",
                "billboard": True,
                "background_padding": [4, 8],
                "pickable": True,
                "auto_highlight": False,
            },
            use_centroid=True,
            legend=None,
            **(params_dict.get("conservancy_text_layer") or {}),
        )
        .call()
    )

    load_mnc_parcels = (
        load_df.validate()
        .set_task_instance_id("load_mnc_parcels")
        .handle_errors()
        .with_tracing()
        .partial(
            file_path=download_mnc_parcels,
            layer=None,
            deserialize_json=False,
            **(params_dict.get("load_mnc_parcels") or {}),
        )
        .call()
    )

    assign_mnc_geom = (
        get_gdf_geom_type_1.validate()
        .set_task_instance_id("assign_mnc_geom")
        .handle_errors()
        .with_tracing()
        .partial(gdf=load_mnc_parcels, **(params_dict.get("assign_mnc_geom") or {}))
        .call()
    )

    create_mnc_parcels_layers = (
        create_deckgl_layer_from_gdf.validate()
        .set_task_instance_id("create_mnc_parcels_layers")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf=assign_mnc_geom,
            style={
                "extruded": False,
                "get_fill_color": [189, 183, 107],
                "get_line_color": [189, 183, 107],
                "get_line_width": 1.55,
                "stroked": True,
                "filled": True,
                "opacity": 0.15,
            },
            legend={"title": "", "values": [{"label": "Parcels", "color": "#bdb76b"}]},
            **(params_dict.get("create_mnc_parcels_layers") or {}),
        )
        .call()
    )

    get_events_data = (
        get_events.validate()
        .set_task_instance_id("get_events_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "reported_by",
                "serial_number",
                "geometry",
                "created_at",
                "event_details",
                "patrols",
            ],
            event_types=[
                "mobile_boma_rep",
                "cattle_count",
                "livestock_predation_rep",
                "illegal_grazing_rep",
            ],
            raise_on_empty=True,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            include_null_geometry=False,
            include_display_values=False,
            **(params_dict.get("get_events_data") or {}),
        )
        .call()
    )

    extract_event_date = (
        extract_column_as_type.validate()
        .set_task_instance_id("extract_event_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_events_data,
            column_name="time",
            output_type="date",
            output_column_name="date",
            **(params_dict.get("extract_event_date") or {}),
        )
        .call()
    )

    events_temporal = (
        add_temporal_index.validate()
        .set_task_instance_id("events_temporal")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_event_date,
            time_col="date",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params_dict.get("events_temporal") or {}),
        )
        .call()
    )

    filter_mobile_boma = (
        filter_df.validate()
        .set_task_instance_id("filter_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_temporal,
            column_name="event_type",
            op="equal",
            value="mobile_boma_rep",
            reset_index=True,
            **(params_dict.get("filter_mobile_boma") or {}),
        )
        .call()
    )

    filter_livestock_predation = (
        filter_df.validate()
        .set_task_instance_id("filter_livestock_predation")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_temporal,
            column_name="event_type",
            op="equal",
            value="livestock_predation_rep",
            reset_index=True,
            **(params_dict.get("filter_livestock_predation") or {}),
        )
        .call()
    )

    filter_cattle_counts = (
        filter_df.validate()
        .set_task_instance_id("filter_cattle_counts")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_temporal,
            column_name="event_type",
            op="equal",
            value="cattle_count",
            reset_index=True,
            **(params_dict.get("filter_cattle_counts") or {}),
        )
        .call()
    )

    filter_illegal_grazing = (
        filter_df.validate()
        .set_task_instance_id("filter_illegal_grazing")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_temporal,
            column_name="event_type",
            op="equal",
            value="illegal_grazing_rep",
            reset_index=True,
            **(params_dict.get("filter_illegal_grazing") or {}),
        )
        .call()
    )

    process_mobile_boma = (
        process_events_details.validate()
        .set_task_instance_id("process_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_mobile_boma,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params_dict.get("process_mobile_boma") or {}),
        )
        .call()
    )

    normalize_mobile_boma = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_mobile_boma,
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_mobile_boma") or {}),
        )
        .call()
    )

    drop_mobile_prefix = (
        drop_column_prefix.validate()
        .set_task_instance_id("drop_mobile_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_mobile_boma,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params_dict.get("drop_mobile_prefix") or {}),
        )
        .call()
    )

    process_livestock_preds = (
        process_events_details.validate()
        .set_task_instance_id("process_livestock_preds")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_livestock_predation,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params_dict.get("process_livestock_preds") or {}),
        )
        .call()
    )

    normalize_livestock_preds = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_livestock_preds")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_livestock_preds,
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_livestock_preds") or {}),
        )
        .call()
    )

    drop_predation_prefix = (
        drop_column_prefix.validate()
        .set_task_instance_id("drop_predation_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_livestock_preds,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params_dict.get("drop_predation_prefix") or {}),
        )
        .call()
    )

    process_cattle_counts = (
        process_events_details.validate()
        .set_task_instance_id("process_cattle_counts")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_cattle_counts,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params_dict.get("process_cattle_counts") or {}),
        )
        .call()
    )

    normalize_cattle_count = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_cattle_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_cattle_counts,
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_cattle_count") or {}),
        )
        .call()
    )

    drop_cattle_prefix = (
        drop_column_prefix.validate()
        .set_task_instance_id("drop_cattle_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_cattle_count,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params_dict.get("drop_cattle_prefix") or {}),
        )
        .call()
    )

    process_illegal_grazing = (
        process_events_details.validate()
        .set_task_instance_id("process_illegal_grazing")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_illegal_grazing,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params_dict.get("process_illegal_grazing") or {}),
        )
        .call()
    )

    normalize_illegal_grazing = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_illegal_grazing")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_illegal_grazing,
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_illegal_grazing") or {}),
        )
        .call()
    )

    drop_illegal_prefix = (
        drop_column_prefix.validate()
        .set_task_instance_id("drop_illegal_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_illegal_grazing,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params_dict.get("drop_illegal_prefix") or {}),
        )
        .call()
    )

    map_mobile_boma = (
        map_columns.validate()
        .set_task_instance_id("map_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_mobile_prefix,
            drop_columns=[],
            retain_columns=[
                "id",
                "date",
                "event_type",
                "geometry",
                "Date of Relocation",
                "Electric Boma Status",
                "Mobile Boma Zone",
                "Nature of the Site",
                "Reason for relocation",
            ],
            rename_columns={},
            raise_if_not_found=False,
            **(params_dict.get("map_mobile_boma") or {}),
        )
        .call()
    )

    summarize_mobile_boma = (
        summarize_df.validate()
        .set_task_instance_id("summarize_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_mobile_boma,
            groupby_cols=["date"],
            summary_params=[
                {
                    "display_name": "boma_events",
                    "aggregator": "nunique",
                    "column": "id",
                    "decimal_places": 0,
                }
            ],
            reset_index=True,
            **(params_dict.get("summarize_mobile_boma") or {}),
        )
        .call()
    )

    add_mobile_summary_row = (
        add_totals_row.validate()
        .set_task_instance_id("add_mobile_summary_row")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            label_col=["date"],
            label="Total",
            df=summarize_mobile_boma,
            **(params_dict.get("add_mobile_summary_row") or {}),
        )
        .call()
    )

    persist_boma_summary = (
        persist_df.validate()
        .set_task_instance_id("persist_boma_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=add_mobile_summary_row,
            filename="mobile_boma_movement_summary_table",
            **(params_dict.get("persist_boma_summary") or {}),
        )
        .call()
    )

    generate_mobile_layers = (
        create_scatterplot_layer.validate()
        .set_task_instance_id("generate_mobile_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_fill_color": [0, 0, 128],
                "get_line_color": [0, 0, 128],
                "get_radius": 3,
                "opacity": 0.55,
                "stroked": True,
            },
            legend={
                "title": "Boma Movements",
                "values": [{"label": "Boma movement", "color": "#000080"}],
                "sort": None,
                "label_suffix": None,
            },
            data_url=None,
            geodataframe=map_mobile_boma,
            **(params_dict.get("generate_mobile_layers") or {}),
        )
        .call()
    )

    global_zoom_value = (
        view_state_deck_gdf.validate()
        .set_task_instance_id("global_zoom_value")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            pitch=0,
            bearing=0,
            gdf=overall_grazing_zones,
            **(params_dict.get("global_zoom_value") or {}),
        )
        .call()
    )

    combine_custom_mobile_boma = (
        combine_deckgl_map_layers.validate()
        .set_task_instance_id("combine_custom_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[
                create_mnc_styled_layers,
                create_mnc_parcels_layers,
                conservancy_text_layer,
            ],
            grouped_layers=generate_mobile_layers,
            **(params_dict.get("combine_custom_mobile_boma") or {}),
        )
        .call()
    )

    draw_mobile_boma = (
        draw_map.validate()
        .set_task_instance_id("draw_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=combine_custom_mobile_boma,
            view_state=global_zoom_value,
            **(params_dict.get("draw_mobile_boma") or {}),
        )
        .call()
    )

    persist_mobile_boma_urls = (
        persist_text.validate()
        .set_task_instance_id("persist_mobile_boma_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_mobile_boma,
            filename="boma_movement_map.html",
            **(params_dict.get("persist_mobile_boma_urls") or {}),
        )
        .call()
    )

    convert_mobile_boma_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_mobile_boma_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_mobile_boma_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_mobile_boma_png") or {}),
        )
        .call()
    )

    map_cattle_count = (
        map_columns.validate()
        .set_task_instance_id("map_cattle_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_cattle_prefix,
            drop_columns=[],
            retain_columns=[
                "date",
                "# cattle in Zone 1 mobile boma",
                "# cattle in Zone 2/3 mobile boma",
                "# cattle in Zone 4",
                "total_cattle_counted_from_all_zones",
            ],
            rename_columns={
                "# cattle in Zone 1 mobile boma": "zone_1",
                "# cattle in Zone 2/3 mobile boma": "zone_2_3",
                "# cattle in Zone 4": "zone_4",
                "total_cattle_counted_from_all_zones": "total_count",
            },
            raise_if_not_found=False,
            **(params_dict.get("map_cattle_count") or {}),
        )
        .call()
    )

    persist_cattle_count = (
        persist_df.validate()
        .set_task_instance_id("persist_cattle_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=map_cattle_count,
            filename="total_cattle_count_summary_table",
            **(params_dict.get("persist_cattle_count") or {}),
        )
        .call()
    )

    map_livestock_predation = (
        map_columns.validate()
        .set_task_instance_id("map_livestock_predation")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_predation_prefix,
            drop_columns=[],
            retain_columns=[
                "id",
                "date",
                "event_type",
                "geometry",
                "Livestock Species",
                "Suspected Predator",
                "Total livestock affected",
            ],
            rename_columns={},
            raise_if_not_found=False,
            **(params_dict.get("map_livestock_predation") or {}),
        )
        .call()
    )

    summarize_predation_events = (
        summarize_df.validate()
        .set_task_instance_id("summarize_predation_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_livestock_predation,
            groupby_cols=["date"],
            summary_params=[
                {
                    "display_name": "livestock_predation_events",
                    "aggregator": "nunique",
                    "column": "id",
                    "decimal_places": 0,
                }
            ],
            reset_index=True,
            **(params_dict.get("summarize_predation_events") or {}),
        )
        .call()
    )

    add_predation_summary_row = (
        add_totals_row.validate()
        .set_task_instance_id("add_predation_summary_row")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            label_col=["date"],
            label="Total",
            df=summarize_predation_events,
            **(params_dict.get("add_predation_summary_row") or {}),
        )
        .call()
    )

    persist_predation_summary = (
        persist_df.validate()
        .set_task_instance_id("persist_predation_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=add_predation_summary_row,
            filename="total_livestock_predation_summary_table",
            **(params_dict.get("persist_predation_summary") or {}),
        )
        .call()
    )

    apply_livestock_colormap = (
        apply_color_map.validate()
        .set_task_instance_id("apply_livestock_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="Livestock Species",
            output_column_name="colors",
            colormap="Set3",
            df=map_livestock_predation,
            **(params_dict.get("apply_livestock_colormap") or {}),
        )
        .call()
    )

    generate_livestock_layers = (
        create_scatterplot_layer.validate()
        .set_task_instance_id("generate_livestock_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_fill_color": "colors",
                "get_line_color": "colors",
                "get_radius": 3,
                "opacity": 0.55,
                "stroked": True,
            },
            legend={
                "title": "Livestock Species",
                "label_column": "Livestock Species",
                "color_column": "colors",
                "sort": "ascending",
                "label_suffix": None,
            },
            data_url=None,
            geodataframe=apply_livestock_colormap,
            **(params_dict.get("generate_livestock_layers") or {}),
        )
        .call()
    )

    combine_custom_livestock = (
        combine_deckgl_map_layers.validate()
        .set_task_instance_id("combine_custom_livestock")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[
                create_conservancy_boundaries,
                create_mnc_parcels_layers,
                conservancy_text_layer,
            ],
            grouped_layers=generate_livestock_layers,
            **(params_dict.get("combine_custom_livestock") or {}),
        )
        .call()
    )

    draw_livestock_map = (
        draw_map.validate()
        .set_task_instance_id("draw_livestock_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=combine_custom_livestock,
            view_state={
                "longitude": 35.2092935880001,
                "latitude": -1.257840580999955,
                "zoom": 9.75,
                "pitch": 0,
                "bearing": 0,
            },
            **(params_dict.get("draw_livestock_map") or {}),
        )
        .call()
    )

    persist_livestock_urls = (
        persist_text.validate()
        .set_task_instance_id("persist_livestock_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_livestock_map,
            filename="livestock_predation_events.html",
            **(params_dict.get("persist_livestock_urls") or {}),
        )
        .call()
    )

    convert_livestock_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_livestock_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_livestock_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_livestock_png") or {}),
        )
        .call()
    )

    map_livestock_summary = (
        map_columns.validate()
        .set_task_instance_id("map_livestock_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_livestock_predation,
            drop_columns=[],
            retain_columns=[
                "date",
                "Livestock Species",
                "Suspected Predator",
                "Total livestock affected",
            ],
            rename_columns={
                "Livestock Species": "livestock_species",
                "Suspected Predator": "suspected_predator",
                "Total livestock affected": "total_livestock_affected",
            },
            raise_if_not_found=False,
            **(params_dict.get("map_livestock_summary") or {}),
        )
        .call()
    )

    replace_livestock_nulls = (
        replace_empty_strings_in_columns.validate()
        .set_task_instance_id("replace_livestock_nulls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_livestock_summary,
            columns=["suspected_predator", "livestock_species"],
            replacement="Unknown",
            strip_whitespace=False,
            missing="ignore",
            **(params_dict.get("replace_livestock_nulls") or {}),
        )
        .call()
    )

    map_livestock_unknown = (
        map_column_values.validate()
        .set_task_instance_id("map_livestock_unknown")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=replace_livestock_nulls,
            columns=["suspected_predator"],
            value_map={"Other (specify in comments)": "Unknown"},
            inplace=True,
            **(params_dict.get("map_livestock_unknown") or {}),
        )
        .call()
    )

    convert_livestock_int = (
        coerce_columns_to_int.validate()
        .set_task_instance_id("convert_livestock_int")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_livestock_unknown,
            columns=["total_livestock_affected"],
            errors="coerce",
            fill_value=0,
            missing="ignore",
            nullable=True,
            **(params_dict.get("convert_livestock_int") or {}),
        )
        .call()
    )

    persist_livestock_summary = (
        persist_df.validate()
        .set_task_instance_id("persist_livestock_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            filename="livestock_predation_summary_table",
            df=convert_livestock_int,
            **(params_dict.get("persist_livestock_summary") or {}),
        )
        .call()
    )

    map_illegal_grazing = (
        map_columns.validate()
        .set_task_instance_id("map_illegal_grazing")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_illegal_prefix,
            drop_columns=[],
            retain_columns=[
                "date",
                "event_type",
                "geometry",
                "Herd Zone",
                "Landowner name",
                "action taken",
            ],
            rename_columns={},
            raise_if_not_found=False,
            **(params_dict.get("map_illegal_grazing") or {}),
        )
        .call()
    )

    generate_illegal_layers = (
        create_scatterplot_layer.validate()
        .set_task_instance_id("generate_illegal_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_fill_color": [0, 0, 128],
                "get_line_color": [0, 0, 128],
                "get_radius": 3,
                "opacity": 0.55,
                "stroked": True,
            },
            legend={
                "title": "Illegal grazing",
                "values": [{"label": "Illegal grazing", "color": "#000080"}],
                "sort": None,
                "label_suffix": None,
            },
            data_url=None,
            geodataframe=map_illegal_grazing,
            **(params_dict.get("generate_illegal_layers") or {}),
        )
        .call()
    )

    combine_custom_illegal = (
        combine_deckgl_map_layers.validate()
        .set_task_instance_id("combine_custom_illegal")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[create_mnc_styled_layers, conservancy_text_layer],
            grouped_layers=generate_illegal_layers,
            **(params_dict.get("combine_custom_illegal") or {}),
        )
        .call()
    )

    draw_illegal_grazing = (
        draw_map.validate()
        .set_task_instance_id("draw_illegal_grazing")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=combine_custom_illegal,
            view_state=global_zoom_value,
            **(params_dict.get("draw_illegal_grazing") or {}),
        )
        .call()
    )

    persist_illegal_urls = (
        persist_text.validate()
        .set_task_instance_id("persist_illegal_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_illegal_grazing,
            filename="illegal_grazing_map.html",
            **(params_dict.get("persist_illegal_urls") or {}),
        )
        .call()
    )

    convert_illegal_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_illegal_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_illegal_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_illegal_png") or {}),
        )
        .call()
    )

    mnc_events_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("mnc_events_dashboard")
        .handle_errors()
        .with_tracing()
        .partial(
            details=workflow_details,
            widgets=[],
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("mnc_events_dashboard") or {}),
        )
        .call()
    )

    return mnc_events_dashboard
