# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_mnc.tasks import (
    create_gdf_from_dict as create_gdf_from_dict,
)
from ecoscope_workflows_ext_ste.tasks import (
    annotate_gdf_dict_with_geom_type as annotate_gdf_dict_with_geom_type,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_custom_text_layer as create_custom_text_layer,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layer_from_gdf as create_deckgl_layer_from_gdf,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layers_from_gdf_dict as create_deckgl_layers_from_gdf_dict,
)
from ecoscope_workflows_ext_ste.tasks import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from ecoscope_workflows_ext_ste.tasks import get_gdf_geom_type as get_gdf_geom_type
from ecoscope_workflows_ext_ste.tasks import split_gdf_by_column as split_gdf_by_column

get_events = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_null_geometry as drop_null_geometry,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_mnc.tasks import add_totals_row as add_totals_row
from ecoscope_workflows_ext_mnc.tasks import convert_to_int as convert_to_int
from ecoscope_workflows_ext_mnc.tasks import (
    exclude_geom_outliers as exclude_geom_outliers,
)
from ecoscope_workflows_ext_mnc.tasks import filter_columns as filter_columns
from ecoscope_workflows_ext_mnc.tasks import map_column_values as map_column_values
from ecoscope_workflows_ext_mnc.tasks import (
    replace_missing_with_label as replace_missing_with_label,
)
from ecoscope_workflows_ext_mnc.tasks import to_sentence_case as to_sentence_case
from ecoscope_workflows_ext_mnc.tasks import transform_columns as transform_columns
from ecoscope_workflows_ext_ste.tasks import (
    combine_deckgl_map_layers as combine_deckgl_map_layers,
)
from ecoscope_workflows_ext_ste.tasks import view_state_deck_gdf as view_state_deck_gdf

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "groupers": [],
        "er_client_name": [],
        "configure_base_maps": [],
        "persist_mnc_gpkg": [],
        "download_mnc_parcels": [],
        "load_comm_shp": ["persist_mnc_gpkg"],
        "split_gdf_by_zone": ["load_comm_shp"],
        "annotate_comm_gdf_dict": ["split_gdf_by_zone"],
        "create_mnc_styled_layers": ["annotate_comm_gdf_dict"],
        "create_conservancy_boundaries": ["annotate_comm_gdf_dict"],
        "conservancy_gdf": ["split_gdf_by_zone"],
        "overall_grazing_zones": ["load_comm_shp"],
        "conservancy_text_layer": ["conservancy_gdf"],
        "load_mnc_parcels": ["download_mnc_parcels"],
        "assign_mnc_geom": ["load_mnc_parcels"],
        "create_mnc_parcels_layers": ["assign_mnc_geom"],
        "get_events_data": ["er_client_name", "time_range"],
        "extract_event_date": ["get_events_data"],
        "events_temporal": ["extract_event_date", "groupers"],
        "filter_mobile_boma": ["events_temporal"],
        "filter_cattle_count": ["events_temporal"],
        "normalize_mb_values": ["filter_mobile_boma"],
        "normalize_cc_values": ["filter_cattle_count"],
        "rename_mobile_boma": ["normalize_mb_values"],
        "rename_cattle_count": ["normalize_cc_values"],
        "rename_boma_values": ["rename_mobile_boma"],
        "calculate_total_boma": ["rename_boma_values"],
        "add_total_boma_row": ["calculate_total_boma"],
        "persist_boma_count_df": ["add_total_boma_row"],
        "filter_cattle_cols": ["rename_cattle_count"],
        "persist_cattle_count_df": ["filter_cattle_cols"],
        "exclude_mb_outliers": ["rename_boma_values"],
        "remove_mb_invalid_geoms": ["exclude_mb_outliers"],
        "apply_mb_colormap": ["remove_mb_invalid_geoms"],
        "generate_mb_layers": ["apply_mb_colormap"],
        "global_zoom_value": ["overall_grazing_zones"],
        "combine_custom_mobile_boma": [
            "create_mnc_styled_layers",
            "create_mnc_parcels_layers",
            "conservancy_text_layer",
            "generate_mb_layers",
        ],
        "draw_mb_map": [
            "configure_base_maps",
            "combine_custom_mobile_boma",
            "global_zoom_value",
        ],
        "persist_mobile_boma_urls": ["draw_mb_map"],
        "filter_predation": ["events_temporal"],
        "normalize_predation_values": ["filter_predation"],
        "rename_livestock_predation": ["normalize_predation_values"],
        "replace_livestock_nulls": ["rename_livestock_predation"],
        "convert_livestock_int": ["replace_livestock_nulls"],
        "livestock_preds_scase": ["convert_livestock_int"],
        "persist_livestock_events_gpkg": ["livestock_preds_scase"],
        "persist_livestock_events_csv": ["livestock_preds_scase"],
        "livestock_predation_summary": ["livestock_preds_scase"],
        "persist_livestock_df": ["livestock_predation_summary"],
        "livestock_events_recorded": ["livestock_preds_scase"],
        "add_total_livestock": ["livestock_events_recorded"],
        "livestock_events_df": ["add_total_livestock"],
        "exclude_livestock_outliers": ["livestock_preds_scase"],
        "remove_livestock_invalid_geoms": ["exclude_livestock_outliers"],
        "apply_livestock_colormap": ["remove_livestock_invalid_geoms"],
        "generate_livestock_layers": ["apply_livestock_colormap"],
        "combine_custom_livestock": [
            "create_conservancy_boundaries",
            "create_mnc_parcels_layers",
            "conservancy_text_layer",
            "generate_livestock_layers",
        ],
        "draw_livestock_map": ["configure_base_maps", "combine_custom_livestock"],
        "persist_livestock_urls": ["draw_livestock_map"],
        "convert_mobile_boma_png": ["persist_mobile_boma_urls"],
        "convert_livestock_png": ["persist_livestock_urls"],
        "mnc_events_dashboard": ["workflow_details", "time_range", "groupers"],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("time_range") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={} | (params_dict.get("groupers") or {}),
            method="call",
        ),
        "er_client_name": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client_name")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("er_client_name") or {}),
            method="call",
        ),
        "configure_base_maps": Node(
            async_task=set_base_maps_pydeck.validate()
            .set_task_instance_id("configure_base_maps")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "base_maps": [
                    {
                        "url": "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
                        "opacity": 1,
                        "max_zoom": 20,
                    },
                ],
            }
            | (params_dict.get("configure_base_maps") or {}),
            method="call",
        ),
        "persist_mnc_gpkg": Node(
            async_task=fetch_and_persist_file.validate()
            .set_task_instance_id("persist_mnc_gpkg")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "url": "https://www.dropbox.com/scl/fi/14rcy4lkwp7xgewj3xf7k/mnc_conservancy.gpkg?rlkey=mtqo7ivxrnvjonm2z1zez6h6f&st=gtdi4vv0&dl=0",
                "output_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "overwrite_existing": False,
                "retries": 3,
                "unzip": False,
            }
            | (params_dict.get("persist_mnc_gpkg") or {}),
            method="call",
        ),
        "download_mnc_parcels": Node(
            async_task=fetch_and_persist_file.validate()
            .set_task_instance_id("download_mnc_parcels")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "url": "https://www.dropbox.com/scl/fi/33rdzy896rh91gtkfs2j3/mnc_across_the_river_parcels.gpkg?rlkey=xima1v0rozc0h9h78esfogx6q&st=o3gkk5p1&dl=0",
                "output_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "overwrite_existing": False,
                "retries": 3,
                "unzip": False,
            }
            | (params_dict.get("download_mnc_parcels") or {}),
            method="call",
        ),
        "load_comm_shp": Node(
            async_task=load_df.validate()
            .set_task_instance_id("load_comm_shp")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "file_path": DependsOn("persist_mnc_gpkg"),
                "layer": None,
                "deserialize_json": False,
            }
            | (params_dict.get("load_comm_shp") or {}),
            method="call",
        ),
        "split_gdf_by_zone": Node(
            async_task=split_gdf_by_column.validate()
            .set_task_instance_id("split_gdf_by_zone")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("load_comm_shp"),
                "column": "grazing_zone",
            }
            | (params_dict.get("split_gdf_by_zone") or {}),
            method="call",
        ),
        "annotate_comm_gdf_dict": Node(
            async_task=annotate_gdf_dict_with_geom_type.validate()
            .set_task_instance_id("annotate_comm_gdf_dict")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "gdf_dict": DependsOn("split_gdf_by_zone"),
            }
            | (params_dict.get("annotate_comm_gdf_dict") or {}),
            method="call",
        ),
        "create_mnc_styled_layers": Node(
            async_task=create_deckgl_layers_from_gdf_dict.validate()
            .set_task_instance_id("create_mnc_styled_layers")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "gdf_dict": DependsOn("annotate_comm_gdf_dict"),
                "styles": {
                    "Conservancy": {
                        "extruded": False,
                        "get_fill_color": [
                            169,
                            169,
                            169,
                        ],
                        "get_line_color": [
                            169,
                            169,
                            169,
                        ],
                        "get_line_width": 4.0,
                        "stroked": True,
                        "filled": False,
                        "opacity": 0.95,
                    },
                    "Conservancy Herd Zone": {
                        "extruded": False,
                        "get_fill_color": [
                            173,
                            255,
                            47,
                        ],
                        "get_line_color": [
                            173,
                            255,
                            47,
                        ],
                        "get_line_width": 1.95,
                        "stroked": True,
                        "filled": True,
                        "opacity": 0.15,
                    },
                    "Grazing Zone 1": {
                        "extruded": False,
                        "get_fill_color": [
                            85,
                            107,
                            47,
                        ],
                        "get_line_color": [
                            85,
                            107,
                            47,
                        ],
                        "get_line_width": 1.95,
                        "stroked": True,
                        "filled": True,
                        "opacity": 0.15,
                    },
                    "Grazing Zone 2": {
                        "extruded": False,
                        "get_fill_color": [
                            0,
                            139,
                            139,
                        ],
                        "get_line_color": [
                            0,
                            139,
                            139,
                        ],
                        "get_line_width": 1.95,
                        "stroked": True,
                        "filled": True,
                        "opacity": 0.15,
                    },
                    "Grazing Zone 3": {
                        "extruded": False,
                        "get_fill_color": [
                            0,
                            100,
                            0,
                        ],
                        "get_line_color": [
                            0,
                            100,
                            0,
                        ],
                        "get_line_width": 1.95,
                        "stroked": True,
                        "filled": True,
                        "opacity": 0.15,
                    },
                    "Grazing Zone 4": {
                        "extruded": False,
                        "get_fill_color": [
                            143,
                            188,
                            139,
                        ],
                        "get_line_color": [
                            143,
                            188,
                            139,
                        ],
                        "get_line_width": 1.95,
                        "stroked": True,
                        "filled": True,
                        "opacity": 0.15,
                    },
                },
                "legends": {
                    "title": "Legend",
                    "values": [
                        {
                            "label": "Conservancy",
                            "color": "#a9a9a9",
                        },
                        {
                            "label": "Conservancy Herd Zone",
                            "color": "#adff2f",
                        },
                        {
                            "label": "Grazing Zone 1",
                            "color": "#556b2f",
                        },
                        {
                            "label": "Grazing Zone 2",
                            "color": "#008b8b",
                        },
                        {
                            "label": "Grazing Zone 3",
                            "color": "#006400",
                        },
                        {
                            "label": "Grazing Zone 4",
                            "color": "#8fbc8b",
                        },
                    ],
                },
            }
            | (params_dict.get("create_mnc_styled_layers") or {}),
            method="call",
        ),
        "create_conservancy_boundaries": Node(
            async_task=create_deckgl_layers_from_gdf_dict.validate()
            .set_task_instance_id("create_conservancy_boundaries")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "gdf_dict": DependsOn("annotate_comm_gdf_dict"),
                "styles": {
                    "Conservancy": {
                        "extruded": False,
                        "get_fill_color": [
                            169,
                            169,
                            169,
                        ],
                        "get_line_color": [
                            169,
                            169,
                            169,
                        ],
                        "get_line_width": 4.0,
                        "stroked": True,
                        "filled": False,
                        "opacity": 0.95,
                    },
                },
                "legends": {
                    "title": "Legend",
                    "values": [
                        {
                            "label": "Boundaries",
                            "color": "#a9a9a9",
                        },
                    ],
                },
            }
            | (params_dict.get("create_conservancy_boundaries") or {}),
            method="call",
        ),
        "conservancy_gdf": Node(
            async_task=create_gdf_from_dict.validate()
            .set_task_instance_id("conservancy_gdf")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "gdf_dict": DependsOn("split_gdf_by_zone"),
                "key": "Conservancy",
            }
            | (params_dict.get("conservancy_gdf") or {}),
            method="call",
        ),
        "overall_grazing_zones": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("overall_grazing_zones")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "column_name": "grazing_zone",
                "op": "ne",
                "value": "Conservancy",
                "df": DependsOn("load_comm_shp"),
                "reset_index": False,
            }
            | (params_dict.get("overall_grazing_zones") or {}),
            method="call",
        ),
        "conservancy_text_layer": Node(
            async_task=create_custom_text_layer.validate()
            .set_task_instance_id("conservancy_text_layer")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("conservancy_gdf"),
                "layer_style": {
                    "get_text": "name",
                    "get_color": [
                        0,
                        0,
                        0,
                        255,
                    ],
                    "get_size": 1500,
                    "size_units": "meters",
                    "size_min_pixels": 70,
                    "size_max_pixels": 100,
                    "size_scale": 2.25,
                    "font_family": "Calibri",
                    "font_weight": "700",
                    "get_text_anchor": "middle",
                    "get_alignment_baseline": "center",
                    "billboard": True,
                    "background_padding": [
                        4,
                        8,
                    ],
                    "pickable": True,
                    "auto_highlight": False,
                },
                "use_centroid": True,
                "legend": None,
            }
            | (params_dict.get("conservancy_text_layer") or {}),
            method="call",
        ),
        "load_mnc_parcels": Node(
            async_task=load_df.validate()
            .set_task_instance_id("load_mnc_parcels")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "file_path": DependsOn("download_mnc_parcels"),
                "layer": None,
                "deserialize_json": False,
            }
            | (params_dict.get("load_mnc_parcels") or {}),
            method="call",
        ),
        "assign_mnc_geom": Node(
            async_task=get_gdf_geom_type.validate()
            .set_task_instance_id("assign_mnc_geom")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("load_mnc_parcels"),
            }
            | (params_dict.get("assign_mnc_geom") or {}),
            method="call",
        ),
        "create_mnc_parcels_layers": Node(
            async_task=create_deckgl_layer_from_gdf.validate()
            .set_task_instance_id("create_mnc_parcels_layers")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("assign_mnc_geom"),
                "style": {
                    "extruded": False,
                    "get_fill_color": [
                        189,
                        183,
                        107,
                    ],
                    "get_line_color": [
                        189,
                        183,
                        107,
                    ],
                    "get_line_width": 1.95,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.15,
                },
                "legend": {
                    "title": "",
                    "values": [
                        {
                            "label": "Parcels",
                            "color": "#bdb76b",
                        },
                    ],
                },
            }
            | (params_dict.get("create_mnc_parcels_layers") or {}),
            method="call",
        ),
        "get_events_data": Node(
            async_task=get_events.validate()
            .set_task_instance_id("get_events_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "event_columns": [
                    "id",
                    "time",
                    "event_type",
                    "event_category",
                    "reported_by",
                    "serial_number",
                    "geometry",
                    "created_at",
                    "event_details",
                    "patrols",
                ],
                "raise_on_empty": True,
                "include_details": True,
                "include_updates": False,
                "include_related_events": False,
                "include_null_geometry": False,
                "include_display_values": False,
            }
            | (params_dict.get("get_events_data") or {}),
            method="call",
        ),
        "extract_event_date": Node(
            async_task=extract_column_as_type.validate()
            .set_task_instance_id("extract_event_date")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("get_events_data"),
                "column_name": "time",
                "output_type": "date",
                "output_column_name": "date",
            }
            | (params_dict.get("extract_event_date") or {}),
            method="call",
        ),
        "events_temporal": Node(
            async_task=add_temporal_index.validate()
            .set_task_instance_id("events_temporal")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_event_date"),
                "time_col": "date",
                "groupers": DependsOn("groupers"),
                "cast_to_datetime": True,
                "format": "mixed",
            }
            | (params_dict.get("events_temporal") or {}),
            method="call",
        ),
        "filter_mobile_boma": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("filter_mobile_boma")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "event_type",
                "op": "equal",
                "value": "mobile_boma_rep",
                "df": DependsOn("events_temporal"),
                "reset_index": False,
            }
            | (params_dict.get("filter_mobile_boma") or {}),
            method="call",
        ),
        "filter_cattle_count": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("filter_cattle_count")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "event_type",
                "op": "equal",
                "value": "cattle_count",
                "df": DependsOn("events_temporal"),
                "reset_index": False,
            }
            | (params_dict.get("filter_cattle_count") or {}),
            method="call",
        ),
        "normalize_mb_values": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_mb_values")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "event_details",
                "df": DependsOn("filter_mobile_boma"),
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_mb_values") or {}),
            method="call",
        ),
        "normalize_cc_values": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_cc_values")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "event_details",
                "df": DependsOn("filter_cattle_count"),
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_cc_values") or {}),
            method="call",
        ),
        "rename_mobile_boma": Node(
            async_task=transform_columns.validate()
            .set_task_instance_id("rename_mobile_boma")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "rename_columns": {
                    "event_details__mobile_boma": "boma",
                },
                "skip_missing_rename": True,
                "required_columns": [
                    "event_details__mobile_boma",
                ],
                "df": DependsOn("normalize_mb_values"),
            }
            | (params_dict.get("rename_mobile_boma") or {}),
            method="call",
        ),
        "rename_cattle_count": Node(
            async_task=transform_columns.validate()
            .set_task_instance_id("rename_cattle_count")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "rename_columns": {
                    "event_details__cattle_in_zone_4": "zone_4",
                    "event_details__cattle_in_zone_1_outside_mobile_boma": "zone_1",
                    "event_details__cattle_in_zone_23_outside_mobile_boma": "zone_2_3",
                    "event_details__total_cattle_counted_from_all_zones": "total_count",
                },
                "skip_missing_rename": True,
                "required_columns": [
                    "event_details__total_cattle_counted_from_all_zones",
                ],
                "df": DependsOn("normalize_cc_values"),
            }
            | (params_dict.get("rename_cattle_count") or {}),
            method="call",
        ),
        "rename_boma_values": Node(
            async_task=map_column_values.validate()
            .set_task_instance_id("rename_boma_values")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_mobile_boma"),
                "columns": [
                    "event_type",
                ],
                "value_map": {
                    "mobile_boma_rep": "Mobile boma",
                },
                "inplace": False,
            }
            | (params_dict.get("rename_boma_values") or {}),
            method="call",
        ),
        "calculate_total_boma": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("calculate_total_boma")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "groupby_cols": [
                    "date",
                ],
                "summary_params": [
                    {
                        "display_name": "total_count",
                        "aggregator": "nunique",
                        "column": "id",
                    },
                ],
                "reset_index": True,
                "df": DependsOn("rename_boma_values"),
            }
            | (params_dict.get("calculate_total_boma") or {}),
            method="call",
        ),
        "add_total_boma_row": Node(
            async_task=add_totals_row.validate()
            .set_task_instance_id("add_total_boma_row")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "label_col": [
                    "date",
                ],
                "label": "Total",
                "df": DependsOn("calculate_total_boma"),
            }
            | (params_dict.get("add_total_boma_row") or {}),
            method="call",
        ),
        "persist_boma_count_df": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_boma_count_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "csv",
                "df": DependsOn("add_total_boma_row"),
                "filename": "total_boma_count_by_date",
            }
            | (params_dict.get("persist_boma_count_df") or {}),
            method="call",
        ),
        "filter_cattle_cols": Node(
            async_task=filter_columns.validate()
            .set_task_instance_id("filter_cattle_cols")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_cattle_count"),
                "columns": [
                    "date",
                    "zone_1",
                    "zone_2_3",
                    "zone_4",
                    "total_count",
                ],
            }
            | (params_dict.get("filter_cattle_cols") or {}),
            method="call",
        ),
        "persist_cattle_count_df": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_cattle_count_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "csv",
                "filename": "mobile_boma_summary_table",
                "df": DependsOn("filter_cattle_cols"),
            }
            | (params_dict.get("persist_cattle_count_df") or {}),
            method="call",
        ),
        "exclude_mb_outliers": Node(
            async_task=exclude_geom_outliers.validate()
            .set_task_instance_id("exclude_mb_outliers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_boma_values"),
                "z_threshold": 3,
            }
            | (params_dict.get("exclude_mb_outliers") or {}),
            method="call",
        ),
        "remove_mb_invalid_geoms": Node(
            async_task=drop_null_geometry.validate()
            .set_task_instance_id("remove_mb_invalid_geoms")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("exclude_mb_outliers"),
                "geometry_column": "geometry",
            }
            | (params_dict.get("remove_mb_invalid_geoms") or {}),
            method="call",
        ),
        "apply_mb_colormap": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("apply_mb_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "input_column_name": "event_type",
                "output_column_name": "event_type_colors",
                "colormap": "tab20",
                "df": DependsOn("remove_mb_invalid_geoms"),
            }
            | (params_dict.get("apply_mb_colormap") or {}),
            method="call",
        ),
        "generate_mb_layers": Node(
            async_task=create_scatterplot_layer.validate()
            .set_task_instance_id("generate_mb_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {
                    "get_fill_color": "event_type_colors",
                    "get_line_color": "event_type_colors",
                    "get_radius": 4,
                    "opacity": 0.75,
                    "stroked": True,
                },
                "legend": {
                    "title": "Boma Movements",
                    "label_column": "event_type",
                    "color_column": "event_type_colors",
                    "sort": "ascending",
                    "label_suffix": None,
                },
                "geodataframe": DependsOn("apply_mb_colormap"),
            }
            | (params_dict.get("generate_mb_layers") or {}),
            method="call",
        ),
        "global_zoom_value": Node(
            async_task=view_state_deck_gdf.validate()
            .set_task_instance_id("global_zoom_value")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "pitch": 0,
                "bearing": 0,
                "gdf": DependsOn("overall_grazing_zones"),
            }
            | (params_dict.get("global_zoom_value") or {}),
            method="call",
        ),
        "combine_custom_mobile_boma": Node(
            async_task=combine_deckgl_map_layers.validate()
            .set_task_instance_id("combine_custom_mobile_boma")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "static_layers": [
                    DependsOn("create_mnc_styled_layers"),
                    DependsOn("create_mnc_parcels_layers"),
                    DependsOn("conservancy_text_layer"),
                ],
                "grouped_layers": DependsOn("generate_mb_layers"),
            }
            | (params_dict.get("combine_custom_mobile_boma") or {}),
            method="call",
        ),
        "draw_mb_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("draw_mb_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("configure_base_maps"),
                "static": False,
                "title": None,
                "max_zoom": 10,
                "legend_style": {
                    "placement": "bottom-right",
                },
                "geo_layers": DependsOn("combine_custom_mobile_boma"),
                "view_state": DependsOn("global_zoom_value"),
            }
            | (params_dict.get("draw_mb_map") or {}),
            method="call",
        ),
        "persist_mobile_boma_urls": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_mobile_boma_urls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("draw_mb_map"),
                "filename": "boma_movement_map.html",
            }
            | (params_dict.get("persist_mobile_boma_urls") or {}),
            method="call",
        ),
        "filter_predation": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("filter_predation")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "event_type",
                "op": "equal",
                "value": "livestock_predation_rep",
                "df": DependsOn("events_temporal"),
                "reset_index": False,
            }
            | (params_dict.get("filter_predation") or {}),
            method="call",
        ),
        "normalize_predation_values": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_predation_values")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "event_details",
                "df": DependsOn("filter_predation"),
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_predation_values") or {}),
            method="call",
        ),
        "rename_livestock_predation": Node(
            async_task=transform_columns.validate()
            .set_task_instance_id("rename_livestock_predation")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "rename_columns": {
                    "event_details__livestockpredation_comments": "livestock_predation_comments",
                    "event_details__livestockpredation_location": "predation_location",
                    "event_details__livestockpredation_causedeath": "predation_cause_of_death",
                    "event_details__livestockpredation_retaliation": "predation_retaliation",
                    "event_details__livestockpredation_supervision": "predation_supervision",
                    "event_details__livestockpredation_predatorcount": "predator_count",
                    "event_details__livestockpredation_killedjuvenile": "killed_juvenile",
                    "event_details__livestockpredation_livestockowner": "livestock_owner",
                    "event_details__livestockpredation_distancetopeople": "distance_to_people",
                    "event_details__livestockpredation_livestockspecies": "livestock_species",
                    "event_details__livestockpredation_livestockaffected": "livestock_affected",
                    "event_details__livestockpredation_suspectedpredator": "suspected_predator",
                    "event_details__livestockpredation_bomacontext": "boma_context",
                    "event_details__livestockpredation_killedadultmale": "killed_adult_male",
                    "event_details__livestockpredation_bomaconstruction": "boma_construction",
                    "event_details__livestockpredation_woundedjuvenile": "wounded_juvenile",
                    "event_details__livestockpredation_woundedadultfemale": "wounded_adult_female",
                    "event_details__livestockpredation_woundedadultmale": "wounded_adult_male",
                    "event_details__livestockpredation_bomaheight": "boma_height",
                    "event_details__livestockpredation_bomavisibility": "boma_visibility",
                },
                "skip_missing_rename": True,
                "required_columns": [
                    "event_details__livestockpredation_livestockaffected",
                    "event_details__livestockpredation_livestockspecies",
                    "event_details__livestockpredation_suspectedpredator",
                ],
                "df": DependsOn("normalize_predation_values"),
            }
            | (params_dict.get("rename_livestock_predation") or {}),
            method="call",
        ),
        "replace_livestock_nulls": Node(
            async_task=replace_missing_with_label.validate()
            .set_task_instance_id("replace_livestock_nulls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_livestock_predation"),
                "columns": [
                    "suspected_predator",
                    "livestock_species",
                ],
                "label": "unknown",
            }
            | (params_dict.get("replace_livestock_nulls") or {}),
            method="call",
        ),
        "convert_livestock_int": Node(
            async_task=convert_to_int.validate()
            .set_task_instance_id("convert_livestock_int")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("replace_livestock_nulls"),
                "columns": [
                    "livestock_affected",
                ],
                "errors": "coerce",
                "fill_value": 0,
                "inplace": False,
            }
            | (params_dict.get("convert_livestock_int") or {}),
            method="call",
        ),
        "livestock_preds_scase": Node(
            async_task=to_sentence_case.validate()
            .set_task_instance_id("livestock_preds_scase")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("convert_livestock_int"),
                "columns": [
                    "suspected_predator",
                    "livestock_species",
                ],
            }
            | (params_dict.get("livestock_preds_scase") or {}),
            method="call",
        ),
        "persist_livestock_events_gpkg": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_livestock_events_gpkg")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "gpkg",
                "filename": "livestock_predation_events",
                "df": DependsOn("livestock_preds_scase"),
            }
            | (params_dict.get("persist_livestock_events_gpkg") or {}),
            method="call",
        ),
        "persist_livestock_events_csv": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_livestock_events_csv")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "csv",
                "filename": "livestock_predation_events",
                "df": DependsOn("livestock_preds_scase"),
            }
            | (params_dict.get("persist_livestock_events_csv") or {}),
            method="call",
        ),
        "livestock_predation_summary": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("livestock_predation_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "groupby_cols": [
                    "date",
                    "suspected_predator",
                    "livestock_species",
                ],
                "summary_params": [
                    {
                        "display_name": "no_affected",
                        "aggregator": "sum",
                        "column": "livestock_affected",
                    },
                ],
                "reset_index": True,
                "df": DependsOn("livestock_preds_scase"),
            }
            | (params_dict.get("livestock_predation_summary") or {}),
            method="call",
        ),
        "persist_livestock_df": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_livestock_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "csv",
                "filename": "livestock_predation_summary_table",
                "df": DependsOn("livestock_predation_summary"),
            }
            | (params_dict.get("persist_livestock_df") or {}),
            method="call",
        ),
        "livestock_events_recorded": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("livestock_events_recorded")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "groupby_cols": [
                    "date",
                ],
                "summary_params": [
                    {
                        "display_name": "no_of_events",
                        "aggregator": "nunique",
                        "column": "id",
                    },
                ],
                "reset_index": True,
                "df": DependsOn("livestock_preds_scase"),
            }
            | (params_dict.get("livestock_events_recorded") or {}),
            method="call",
        ),
        "add_total_livestock": Node(
            async_task=add_totals_row.validate()
            .set_task_instance_id("add_total_livestock")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "label_col": [
                    "date",
                ],
                "label": "Total",
                "df": DependsOn("livestock_events_recorded"),
            }
            | (params_dict.get("add_total_livestock") or {}),
            method="call",
        ),
        "livestock_events_df": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("livestock_events_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "csv",
                "df": DependsOn("add_total_livestock"),
                "filename": "livestock_events_recorded_by_date",
            }
            | (params_dict.get("livestock_events_df") or {}),
            method="call",
        ),
        "exclude_livestock_outliers": Node(
            async_task=exclude_geom_outliers.validate()
            .set_task_instance_id("exclude_livestock_outliers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("livestock_preds_scase"),
                "z_threshold": 3,
            }
            | (params_dict.get("exclude_livestock_outliers") or {}),
            method="call",
        ),
        "remove_livestock_invalid_geoms": Node(
            async_task=drop_null_geometry.validate()
            .set_task_instance_id("remove_livestock_invalid_geoms")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("exclude_livestock_outliers"),
                "geometry_column": "geometry",
            }
            | (params_dict.get("remove_livestock_invalid_geoms") or {}),
            method="call",
        ),
        "apply_livestock_colormap": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("apply_livestock_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "input_column_name": "livestock_species",
                "output_column_name": "colors",
                "colormap": "tab20",
                "df": DependsOn("remove_livestock_invalid_geoms"),
            }
            | (params_dict.get("apply_livestock_colormap") or {}),
            method="call",
        ),
        "generate_livestock_layers": Node(
            async_task=create_scatterplot_layer.validate()
            .set_task_instance_id("generate_livestock_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {
                    "get_fill_color": "colors",
                    "get_line_color": "colors",
                    "get_radius": 4,
                    "opacity": 0.75,
                    "stroked": True,
                },
                "legend": {
                    "title": "Livestock Species",
                    "label_column": "livestock_species",
                    "color_column": "colors",
                    "sort": "ascending",
                    "label_suffix": None,
                },
                "geodataframe": DependsOn("apply_livestock_colormap"),
            }
            | (params_dict.get("generate_livestock_layers") or {}),
            method="call",
        ),
        "combine_custom_livestock": Node(
            async_task=combine_deckgl_map_layers.validate()
            .set_task_instance_id("combine_custom_livestock")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "static_layers": [
                    DependsOn("create_conservancy_boundaries"),
                    DependsOn("create_mnc_parcels_layers"),
                    DependsOn("conservancy_text_layer"),
                ],
                "grouped_layers": DependsOn("generate_livestock_layers"),
            }
            | (params_dict.get("combine_custom_livestock") or {}),
            method="call",
        ),
        "draw_livestock_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("draw_livestock_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("configure_base_maps"),
                "static": False,
                "title": None,
                "max_zoom": 10,
                "legend_style": {
                    "placement": "bottom-right",
                },
                "geo_layers": DependsOn("combine_custom_livestock"),
                "view_state": {
                    "longitude": 35.2092935880001,
                    "latitude": -1.257840580999955,
                    "zoom": 9.75,
                    "pitch": 0,
                    "bearing": 0,
                },
            }
            | (params_dict.get("draw_livestock_map") or {}),
            method="call",
        ),
        "persist_livestock_urls": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_livestock_urls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("draw_livestock_map"),
                "filename": "livestock_predation_events.html",
            }
            | (params_dict.get("persist_livestock_urls") or {}),
            method="call",
        ),
        "convert_mobile_boma_png": Node(
            async_task=html_to_png.validate()
            .set_task_instance_id("convert_mobile_boma_png")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "html_path": DependsOn("persist_mobile_boma_urls"),
                "config": {
                    "full_page": False,
                    "device_scale_factor": 2.0,
                    "wait_for_timeout": 40000,
                    "max_concurrent_pages": 1,
                },
            }
            | (params_dict.get("convert_mobile_boma_png") or {}),
            method="call",
        ),
        "convert_livestock_png": Node(
            async_task=html_to_png.validate()
            .set_task_instance_id("convert_livestock_png")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "html_path": DependsOn("persist_livestock_urls"),
                "config": {
                    "full_page": False,
                    "device_scale_factor": 2.0,
                    "wait_for_timeout": 40000,
                    "max_concurrent_pages": 1,
                },
            }
            | (params_dict.get("convert_livestock_png") or {}),
            method="call",
        ),
        "mnc_events_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("mnc_events_dashboard")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "time_range": DependsOn("time_range"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("mnc_events_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
