# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_mnc.tasks import (
    create_gdf_from_dict as create_gdf_from_dict,
)
from ecoscope_workflows_ext_ste.tasks import (
    annotate_gdf_dict_with_geom_type as annotate_gdf_dict_with_geom_type_1,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_custom_text_layer as create_custom_text_layer,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layer_from_gdf as create_deckgl_layer_from_gdf,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layers_from_gdf_dict as create_deckgl_layers_from_gdf_dict,
)
from ecoscope_workflows_ext_ste.tasks import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from ecoscope_workflows_ext_ste.tasks import get_gdf_geom_type as get_gdf_geom_type_1
from ecoscope_workflows_ext_ste.tasks import split_gdf_by_column as split_gdf_by_column

get_events = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.transformation import (
    coerce_columns_to_int as coerce_columns_to_int,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    replace_empty_strings_in_columns as replace_empty_strings_in_columns,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_mnc.tasks import add_totals_row as add_totals_row
from ecoscope_workflows_ext_mnc.tasks import map_column_values as map_column_values
from ecoscope_workflows_ext_ste.tasks import (
    combine_deckgl_map_layers as combine_deckgl_map_layers,
)
from ecoscope_workflows_ext_ste.tasks import view_state_deck_gdf as view_state_deck_gdf

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "groupers": [],
        "er_client_name": [],
        "configure_base_maps": [],
        "persist_mnc_gpkg": [],
        "download_mnc_parcels": [],
        "load_comm_shp": ["persist_mnc_gpkg"],
        "split_gdf_by_zone": ["load_comm_shp"],
        "annotate_comm_gdf_dict": ["split_gdf_by_zone"],
        "create_mnc_styled_layers": ["annotate_comm_gdf_dict"],
        "create_conservancy_boundaries": ["annotate_comm_gdf_dict"],
        "conservancy_gdf": ["split_gdf_by_zone"],
        "overall_grazing_zones": ["load_comm_shp"],
        "conservancy_text_layer": ["conservancy_gdf"],
        "load_mnc_parcels": ["download_mnc_parcels"],
        "assign_mnc_geom": ["load_mnc_parcels"],
        "create_mnc_parcels_layers": ["assign_mnc_geom"],
        "get_events_data": ["er_client_name", "time_range"],
        "extract_event_date": ["get_events_data"],
        "events_temporal": ["extract_event_date", "groupers"],
        "filter_mobile_boma": ["events_temporal"],
        "filter_livestock_predation": ["events_temporal"],
        "filter_cattle_counts": ["events_temporal"],
        "filter_illegal_grazing": ["events_temporal"],
        "process_mobile_boma": ["filter_mobile_boma", "er_client_name"],
        "normalize_mobile_boma": ["process_mobile_boma"],
        "drop_mobile_prefix": ["normalize_mobile_boma"],
        "process_livestock_preds": ["filter_livestock_predation", "er_client_name"],
        "normalize_livestock_preds": ["process_livestock_preds"],
        "drop_predation_prefix": ["normalize_livestock_preds"],
        "process_cattle_counts": ["filter_cattle_counts", "er_client_name"],
        "normalize_cattle_count": ["process_cattle_counts"],
        "drop_cattle_prefix": ["normalize_cattle_count"],
        "process_illegal_grazing": ["filter_illegal_grazing", "er_client_name"],
        "normalize_illegal_grazing": ["process_illegal_grazing"],
        "drop_illegal_prefix": ["normalize_illegal_grazing"],
        "map_mobile_boma": ["drop_mobile_prefix"],
        "summarize_mobile_boma": ["map_mobile_boma"],
        "add_mobile_summary_row": ["summarize_mobile_boma"],
        "persist_boma_summary": ["add_mobile_summary_row"],
        "generate_mobile_layers": ["map_mobile_boma"],
        "global_zoom_value": ["overall_grazing_zones"],
        "combine_custom_mobile_boma": [
            "create_mnc_styled_layers",
            "create_mnc_parcels_layers",
            "conservancy_text_layer",
            "generate_mobile_layers",
        ],
        "draw_mobile_boma": [
            "configure_base_maps",
            "combine_custom_mobile_boma",
            "global_zoom_value",
        ],
        "persist_mobile_boma_urls": ["draw_mobile_boma"],
        "convert_mobile_boma_png": ["persist_mobile_boma_urls"],
        "map_cattle_count": ["drop_cattle_prefix"],
        "persist_cattle_count": ["map_cattle_count"],
        "map_livestock_predation": ["drop_predation_prefix"],
        "summarize_predation_events": ["map_livestock_predation"],
        "add_predation_summary_row": ["summarize_predation_events"],
        "persist_predation_summary": ["add_predation_summary_row"],
        "apply_livestock_colormap": ["map_livestock_predation"],
        "generate_livestock_layers": ["apply_livestock_colormap"],
        "combine_custom_livestock": [
            "create_conservancy_boundaries",
            "create_mnc_parcels_layers",
            "conservancy_text_layer",
            "generate_livestock_layers",
        ],
        "draw_livestock_map": ["configure_base_maps", "combine_custom_livestock"],
        "persist_livestock_urls": ["draw_livestock_map"],
        "convert_livestock_png": ["persist_livestock_urls"],
        "map_livestock_summary": ["map_livestock_predation"],
        "replace_livestock_nulls": ["map_livestock_summary"],
        "map_livestock_unknown": ["replace_livestock_nulls"],
        "convert_livestock_int": ["map_livestock_unknown"],
        "persist_livestock_summary": ["convert_livestock_int"],
        "map_illegal_grazing": ["drop_illegal_prefix"],
        "generate_illegal_layers": ["map_illegal_grazing"],
        "combine_custom_illegal": [
            "create_mnc_styled_layers",
            "conservancy_text_layer",
            "generate_illegal_layers",
        ],
        "draw_illegal_grazing": [
            "configure_base_maps",
            "combine_custom_illegal",
            "global_zoom_value",
        ],
        "persist_illegal_urls": ["draw_illegal_grazing"],
        "convert_illegal_png": ["persist_illegal_urls"],
        "mnc_events_dashboard": ["workflow_details", "time_range", "groupers"],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("time_range") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={} | (params_dict.get("groupers") or {}),
            method="call",
        ),
        "er_client_name": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client_name")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("er_client_name") or {}),
            method="call",
        ),
        "configure_base_maps": Node(
            async_task=set_base_maps_pydeck.validate()
            .set_task_instance_id("configure_base_maps")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "base_maps": [
                    {
                        "url": "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
                        "opacity": 0.8,
                        "max_zoom": 20,
                    },
                    {
                        "url": "https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places_Alternate/MapServer/tile/{z}/{y}/{x}",
                        "opacity": 0.35,
                        "max_zoom": 20,
                    },
                ],
            }
            | (params_dict.get("configure_base_maps") or {}),
            method="call",
        ),
        "persist_mnc_gpkg": Node(
            async_task=fetch_and_persist_file.validate()
            .set_task_instance_id("persist_mnc_gpkg")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "url": "https://www.dropbox.com/scl/fi/14rcy4lkwp7xgewj3xf7k/mnc_conservancy.gpkg?rlkey=mtqo7ivxrnvjonm2z1zez6h6f&st=gtdi4vv0&dl=0",
                "output_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "overwrite_existing": False,
                "retries": 3,
                "unzip": False,
            }
            | (params_dict.get("persist_mnc_gpkg") or {}),
            method="call",
        ),
        "download_mnc_parcels": Node(
            async_task=fetch_and_persist_file.validate()
            .set_task_instance_id("download_mnc_parcels")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "url": "https://www.dropbox.com/scl/fi/33rdzy896rh91gtkfs2j3/mnc_across_the_river_parcels.gpkg?rlkey=xima1v0rozc0h9h78esfogx6q&st=o3gkk5p1&dl=0",
                "output_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "overwrite_existing": False,
                "retries": 3,
                "unzip": False,
            }
            | (params_dict.get("download_mnc_parcels") or {}),
            method="call",
        ),
        "load_comm_shp": Node(
            async_task=load_df.validate()
            .set_task_instance_id("load_comm_shp")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "file_path": DependsOn("persist_mnc_gpkg"),
                "layer": None,
                "deserialize_json": False,
            }
            | (params_dict.get("load_comm_shp") or {}),
            method="call",
        ),
        "split_gdf_by_zone": Node(
            async_task=split_gdf_by_column.validate()
            .set_task_instance_id("split_gdf_by_zone")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("load_comm_shp"),
                "column": "grazing_zone",
            }
            | (params_dict.get("split_gdf_by_zone") or {}),
            method="call",
        ),
        "annotate_comm_gdf_dict": Node(
            async_task=annotate_gdf_dict_with_geom_type_1.validate()
            .set_task_instance_id("annotate_comm_gdf_dict")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "gdf_dict": DependsOn("split_gdf_by_zone"),
            }
            | (params_dict.get("annotate_comm_gdf_dict") or {}),
            method="call",
        ),
        "create_mnc_styled_layers": Node(
            async_task=create_deckgl_layers_from_gdf_dict.validate()
            .set_task_instance_id("create_mnc_styled_layers")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "gdf_dict": DependsOn("annotate_comm_gdf_dict"),
                "styles": {
                    "Conservancy": {
                        "extruded": False,
                        "get_fill_color": [
                            119,
                            136,
                            153,
                        ],
                        "get_line_color": [
                            119,
                            136,
                            153,
                        ],
                        "get_line_width": 1.55,
                        "stroked": True,
                        "filled": False,
                        "opacity": 0.7,
                    },
                    "Conservancy Herd Zone": {
                        "extruded": False,
                        "get_fill_color": [
                            173,
                            255,
                            47,
                        ],
                        "get_line_color": [
                            173,
                            255,
                            47,
                        ],
                        "get_line_width": 1.25,
                        "stroked": True,
                        "filled": True,
                        "opacity": 0.1,
                    },
                    "Grazing Zone 1": {
                        "extruded": False,
                        "get_fill_color": [
                            85,
                            107,
                            47,
                        ],
                        "get_line_color": [
                            85,
                            107,
                            47,
                        ],
                        "get_line_width": 1.25,
                        "stroked": True,
                        "filled": True,
                        "opacity": 0.1,
                    },
                    "Grazing Zone 2": {
                        "extruded": False,
                        "get_fill_color": [
                            0,
                            139,
                            139,
                        ],
                        "get_line_color": [
                            0,
                            139,
                            139,
                        ],
                        "get_line_width": 1.25,
                        "stroked": True,
                        "filled": True,
                        "opacity": 0.1,
                    },
                    "Grazing Zone 3": {
                        "extruded": False,
                        "get_fill_color": [
                            0,
                            100,
                            0,
                        ],
                        "get_line_color": [
                            0,
                            100,
                            0,
                        ],
                        "get_line_width": 1.25,
                        "stroked": True,
                        "filled": True,
                        "opacity": 0.1,
                    },
                    "Grazing Zone 4": {
                        "extruded": False,
                        "get_fill_color": [
                            143,
                            188,
                            139,
                        ],
                        "get_line_color": [
                            143,
                            188,
                            139,
                        ],
                        "get_line_width": 1.25,
                        "stroked": True,
                        "filled": True,
                        "opacity": 0.7,
                    },
                },
                "legends": {
                    "title": "Legend",
                    "values": [
                        {
                            "label": "Conservancy Boundaries",
                            "color": "#778899",
                        },
                        {
                            "label": "Conservancy Herd Zone",
                            "color": "#adff2f",
                        },
                        {
                            "label": "Grazing Zone 1",
                            "color": "#556b2f",
                        },
                        {
                            "label": "Grazing Zone 2",
                            "color": "#008b8b",
                        },
                        {
                            "label": "Grazing Zone 3",
                            "color": "#006400",
                        },
                        {
                            "label": "Grazing Zone 4",
                            "color": "#8fbc8b",
                        },
                    ],
                },
            }
            | (params_dict.get("create_mnc_styled_layers") or {}),
            method="call",
        ),
        "create_conservancy_boundaries": Node(
            async_task=create_deckgl_layers_from_gdf_dict.validate()
            .set_task_instance_id("create_conservancy_boundaries")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "gdf_dict": DependsOn("annotate_comm_gdf_dict"),
                "styles": {
                    "Conservancy": {
                        "extruded": False,
                        "get_fill_color": [
                            119,
                            136,
                            153,
                        ],
                        "get_line_color": [
                            119,
                            136,
                            153,
                        ],
                        "get_line_width": 1.55,
                        "stroked": True,
                        "filled": False,
                        "opacity": 0.7,
                    },
                },
                "legends": {
                    "title": "Legend",
                    "values": [
                        {
                            "label": "Conservancy Boundaries",
                            "color": "#778899",
                        },
                    ],
                },
            }
            | (params_dict.get("create_conservancy_boundaries") or {}),
            method="call",
        ),
        "conservancy_gdf": Node(
            async_task=create_gdf_from_dict.validate()
            .set_task_instance_id("conservancy_gdf")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "gdf_dict": DependsOn("split_gdf_by_zone"),
                "key": "Conservancy",
            }
            | (params_dict.get("conservancy_gdf") or {}),
            method="call",
        ),
        "overall_grazing_zones": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("overall_grazing_zones")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "column_name": "grazing_zone",
                "op": "ne",
                "value": "Conservancy",
                "df": DependsOn("load_comm_shp"),
                "reset_index": False,
            }
            | (params_dict.get("overall_grazing_zones") or {}),
            method="call",
        ),
        "conservancy_text_layer": Node(
            async_task=create_custom_text_layer.validate()
            .set_task_instance_id("conservancy_text_layer")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("conservancy_gdf"),
                "layer_style": {
                    "get_text": "name",
                    "get_color": [
                        0,
                        0,
                        0,
                        255,
                    ],
                    "get_size": 1500,
                    "size_units": "meters",
                    "size_min_pixels": 70,
                    "size_max_pixels": 100,
                    "size_scale": 2.25,
                    "font_family": "Calibri",
                    "font_weight": "normal",
                    "get_text_anchor": "middle",
                    "get_alignment_baseline": "center",
                    "billboard": True,
                    "background_padding": [
                        4,
                        8,
                    ],
                    "pickable": True,
                    "auto_highlight": False,
                },
                "use_centroid": True,
                "legend": None,
            }
            | (params_dict.get("conservancy_text_layer") or {}),
            method="call",
        ),
        "load_mnc_parcels": Node(
            async_task=load_df.validate()
            .set_task_instance_id("load_mnc_parcels")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "file_path": DependsOn("download_mnc_parcels"),
                "layer": None,
                "deserialize_json": False,
            }
            | (params_dict.get("load_mnc_parcels") or {}),
            method="call",
        ),
        "assign_mnc_geom": Node(
            async_task=get_gdf_geom_type_1.validate()
            .set_task_instance_id("assign_mnc_geom")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("load_mnc_parcels"),
            }
            | (params_dict.get("assign_mnc_geom") or {}),
            method="call",
        ),
        "create_mnc_parcels_layers": Node(
            async_task=create_deckgl_layer_from_gdf.validate()
            .set_task_instance_id("create_mnc_parcels_layers")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("assign_mnc_geom"),
                "style": {
                    "extruded": False,
                    "get_fill_color": [
                        189,
                        183,
                        107,
                    ],
                    "get_line_color": [
                        189,
                        183,
                        107,
                    ],
                    "get_line_width": 1.55,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.15,
                },
                "legend": {
                    "title": "",
                    "values": [
                        {
                            "label": "Parcels",
                            "color": "#bdb76b",
                        },
                    ],
                },
            }
            | (params_dict.get("create_mnc_parcels_layers") or {}),
            method="call",
        ),
        "get_events_data": Node(
            async_task=get_events.validate()
            .set_task_instance_id("get_events_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "event_columns": [
                    "id",
                    "time",
                    "event_type",
                    "event_category",
                    "reported_by",
                    "serial_number",
                    "geometry",
                    "created_at",
                    "event_details",
                    "patrols",
                ],
                "event_types": [
                    "mobile_boma_rep",
                    "cattle_count",
                    "livestock_predation_rep",
                    "illegal_grazing_rep",
                ],
                "raise_on_empty": True,
                "include_details": True,
                "include_updates": False,
                "include_related_events": False,
                "include_null_geometry": False,
                "include_display_values": False,
            }
            | (params_dict.get("get_events_data") or {}),
            method="call",
        ),
        "extract_event_date": Node(
            async_task=extract_column_as_type.validate()
            .set_task_instance_id("extract_event_date")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("get_events_data"),
                "column_name": "time",
                "output_type": "date",
                "output_column_name": "date",
            }
            | (params_dict.get("extract_event_date") or {}),
            method="call",
        ),
        "events_temporal": Node(
            async_task=add_temporal_index.validate()
            .set_task_instance_id("events_temporal")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_event_date"),
                "time_col": "date",
                "groupers": DependsOn("groupers"),
                "cast_to_datetime": True,
                "format": "mixed",
            }
            | (params_dict.get("events_temporal") or {}),
            method="call",
        ),
        "filter_mobile_boma": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("filter_mobile_boma")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("events_temporal"),
                "column_name": "event_type",
                "op": "equal",
                "value": "mobile_boma_rep",
                "reset_index": True,
            }
            | (params_dict.get("filter_mobile_boma") or {}),
            method="call",
        ),
        "filter_livestock_predation": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("filter_livestock_predation")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("events_temporal"),
                "column_name": "event_type",
                "op": "equal",
                "value": "livestock_predation_rep",
                "reset_index": True,
            }
            | (params_dict.get("filter_livestock_predation") or {}),
            method="call",
        ),
        "filter_cattle_counts": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("filter_cattle_counts")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("events_temporal"),
                "column_name": "event_type",
                "op": "equal",
                "value": "cattle_count",
                "reset_index": True,
            }
            | (params_dict.get("filter_cattle_counts") or {}),
            method="call",
        ),
        "filter_illegal_grazing": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("filter_illegal_grazing")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("events_temporal"),
                "column_name": "event_type",
                "op": "equal",
                "value": "illegal_grazing_rep",
                "reset_index": True,
            }
            | (params_dict.get("filter_illegal_grazing") or {}),
            method="call",
        ),
        "process_mobile_boma": Node(
            async_task=process_events_details.validate()
            .set_task_instance_id("process_mobile_boma")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("filter_mobile_boma"),
                "client": DependsOn("er_client_name"),
                "map_to_titles": True,
                "ordered": True,
            }
            | (params_dict.get("process_mobile_boma") or {}),
            method="call",
        ),
        "normalize_mobile_boma": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_mobile_boma")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("process_mobile_boma"),
                "column": "event_details",
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_mobile_boma") or {}),
            method="call",
        ),
        "drop_mobile_prefix": Node(
            async_task=drop_column_prefix.validate()
            .set_task_instance_id("drop_mobile_prefix")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("normalize_mobile_boma"),
                "prefix": "event_details__",
                "duplicate_strategy": "keep_original",
            }
            | (params_dict.get("drop_mobile_prefix") or {}),
            method="call",
        ),
        "process_livestock_preds": Node(
            async_task=process_events_details.validate()
            .set_task_instance_id("process_livestock_preds")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("filter_livestock_predation"),
                "client": DependsOn("er_client_name"),
                "map_to_titles": True,
                "ordered": True,
            }
            | (params_dict.get("process_livestock_preds") or {}),
            method="call",
        ),
        "normalize_livestock_preds": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_livestock_preds")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("process_livestock_preds"),
                "column": "event_details",
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_livestock_preds") or {}),
            method="call",
        ),
        "drop_predation_prefix": Node(
            async_task=drop_column_prefix.validate()
            .set_task_instance_id("drop_predation_prefix")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("normalize_livestock_preds"),
                "prefix": "event_details__",
                "duplicate_strategy": "keep_original",
            }
            | (params_dict.get("drop_predation_prefix") or {}),
            method="call",
        ),
        "process_cattle_counts": Node(
            async_task=process_events_details.validate()
            .set_task_instance_id("process_cattle_counts")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("filter_cattle_counts"),
                "client": DependsOn("er_client_name"),
                "map_to_titles": True,
                "ordered": True,
            }
            | (params_dict.get("process_cattle_counts") or {}),
            method="call",
        ),
        "normalize_cattle_count": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_cattle_count")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("process_cattle_counts"),
                "column": "event_details",
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_cattle_count") or {}),
            method="call",
        ),
        "drop_cattle_prefix": Node(
            async_task=drop_column_prefix.validate()
            .set_task_instance_id("drop_cattle_prefix")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("normalize_cattle_count"),
                "prefix": "event_details__",
                "duplicate_strategy": "keep_original",
            }
            | (params_dict.get("drop_cattle_prefix") or {}),
            method="call",
        ),
        "process_illegal_grazing": Node(
            async_task=process_events_details.validate()
            .set_task_instance_id("process_illegal_grazing")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("filter_illegal_grazing"),
                "client": DependsOn("er_client_name"),
                "map_to_titles": True,
                "ordered": True,
            }
            | (params_dict.get("process_illegal_grazing") or {}),
            method="call",
        ),
        "normalize_illegal_grazing": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_illegal_grazing")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("process_illegal_grazing"),
                "column": "event_details",
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_illegal_grazing") or {}),
            method="call",
        ),
        "drop_illegal_prefix": Node(
            async_task=drop_column_prefix.validate()
            .set_task_instance_id("drop_illegal_prefix")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("normalize_illegal_grazing"),
                "prefix": "event_details__",
                "duplicate_strategy": "keep_original",
            }
            | (params_dict.get("drop_illegal_prefix") or {}),
            method="call",
        ),
        "map_mobile_boma": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("map_mobile_boma")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("drop_mobile_prefix"),
                "retain_columns": [
                    "id",
                    "date",
                    "event_type",
                    "geometry",
                    "Date of Relocation",
                    "Electric Boma Status",
                    "Mobile Boma Zone",
                    "Nature of the Site",
                    "Reason for relocation",
                ],
                "raise_if_not_found": False,
            }
            | (params_dict.get("map_mobile_boma") or {}),
            method="call",
        ),
        "summarize_mobile_boma": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("summarize_mobile_boma")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("map_mobile_boma"),
                "groupby_cols": [
                    "date",
                ],
                "summary_params": [
                    {
                        "display_name": "boma_events",
                        "aggregator": "nunique",
                        "column": "id",
                        "decimal_places": 0,
                    },
                ],
                "reset_index": True,
            }
            | (params_dict.get("summarize_mobile_boma") or {}),
            method="call",
        ),
        "add_mobile_summary_row": Node(
            async_task=add_totals_row.validate()
            .set_task_instance_id("add_mobile_summary_row")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "label_col": [
                    "date",
                ],
                "label": "Total",
                "df": DependsOn("summarize_mobile_boma"),
            }
            | (params_dict.get("add_mobile_summary_row") or {}),
            method="call",
        ),
        "persist_boma_summary": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_boma_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "csv",
                "df": DependsOn("add_mobile_summary_row"),
                "filename": "mobile_boma_movement_summary_table",
            }
            | (params_dict.get("persist_boma_summary") or {}),
            method="call",
        ),
        "generate_mobile_layers": Node(
            async_task=create_scatterplot_layer.validate()
            .set_task_instance_id("generate_mobile_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {
                    "get_fill_color": [
                        0,
                        0,
                        128,
                    ],
                    "get_line_color": [
                        0,
                        0,
                        128,
                    ],
                    "get_radius": 3,
                    "opacity": 0.55,
                    "stroked": True,
                },
                "legend": {
                    "title": "Boma Movements",
                    "values": [
                        {
                            "label": "Boma movement",
                            "color": "#000080",
                        },
                    ],
                    "sort": None,
                    "label_suffix": None,
                },
                "data_url": None,
                "geodataframe": DependsOn("map_mobile_boma"),
            }
            | (params_dict.get("generate_mobile_layers") or {}),
            method="call",
        ),
        "global_zoom_value": Node(
            async_task=view_state_deck_gdf.validate()
            .set_task_instance_id("global_zoom_value")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "pitch": 0,
                "bearing": 0,
                "gdf": DependsOn("overall_grazing_zones"),
            }
            | (params_dict.get("global_zoom_value") or {}),
            method="call",
        ),
        "combine_custom_mobile_boma": Node(
            async_task=combine_deckgl_map_layers.validate()
            .set_task_instance_id("combine_custom_mobile_boma")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "static_layers": [
                    DependsOn("create_mnc_styled_layers"),
                    DependsOn("create_mnc_parcels_layers"),
                    DependsOn("conservancy_text_layer"),
                ],
                "grouped_layers": DependsOn("generate_mobile_layers"),
            }
            | (params_dict.get("combine_custom_mobile_boma") or {}),
            method="call",
        ),
        "draw_mobile_boma": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("draw_mobile_boma")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("configure_base_maps"),
                "static": False,
                "title": None,
                "max_zoom": 10,
                "legend_style": {
                    "placement": "bottom-right",
                },
                "geo_layers": DependsOn("combine_custom_mobile_boma"),
                "view_state": DependsOn("global_zoom_value"),
            }
            | (params_dict.get("draw_mobile_boma") or {}),
            method="call",
        ),
        "persist_mobile_boma_urls": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_mobile_boma_urls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("draw_mobile_boma"),
                "filename": "boma_movement_map.html",
            }
            | (params_dict.get("persist_mobile_boma_urls") or {}),
            method="call",
        ),
        "convert_mobile_boma_png": Node(
            async_task=html_to_png.validate()
            .set_task_instance_id("convert_mobile_boma_png")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "html_path": DependsOn("persist_mobile_boma_urls"),
                "config": {
                    "full_page": False,
                    "device_scale_factor": 2.0,
                    "wait_for_timeout": 40000,
                    "max_concurrent_pages": 1,
                },
            }
            | (params_dict.get("convert_mobile_boma_png") or {}),
            method="call",
        ),
        "map_cattle_count": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("map_cattle_count")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("drop_cattle_prefix"),
                "retain_columns": [
                    "date",
                    "# cattle in Zone 1 mobile boma",
                    "# cattle in Zone 2/3 mobile boma",
                    "# cattle in Zone 4",
                    "total_cattle_counted_from_all_zones",
                ],
                "rename_columns": {
                    "# cattle in Zone 1 mobile boma": "zone_1",
                    "# cattle in Zone 2/3 mobile boma": "zone_2_3",
                    "# cattle in Zone 4": "zone_4",
                    "total_cattle_counted_from_all_zones": "total_count",
                },
                "raise_if_not_found": False,
            }
            | (params_dict.get("map_cattle_count") or {}),
            method="call",
        ),
        "persist_cattle_count": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_cattle_count")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "csv",
                "df": DependsOn("map_cattle_count"),
                "filename": "total_cattle_count_summary_table",
            }
            | (params_dict.get("persist_cattle_count") or {}),
            method="call",
        ),
        "map_livestock_predation": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("map_livestock_predation")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("drop_predation_prefix"),
                "retain_columns": [
                    "id",
                    "date",
                    "event_type",
                    "geometry",
                    "Livestock Species",
                    "Suspected Predator",
                    "Total livestock affected",
                ],
                "raise_if_not_found": False,
            }
            | (params_dict.get("map_livestock_predation") or {}),
            method="call",
        ),
        "summarize_predation_events": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("summarize_predation_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("map_livestock_predation"),
                "groupby_cols": [
                    "date",
                ],
                "summary_params": [
                    {
                        "display_name": "livestock_predation_events",
                        "aggregator": "nunique",
                        "column": "id",
                        "decimal_places": 0,
                    },
                ],
                "reset_index": True,
            }
            | (params_dict.get("summarize_predation_events") or {}),
            method="call",
        ),
        "add_predation_summary_row": Node(
            async_task=add_totals_row.validate()
            .set_task_instance_id("add_predation_summary_row")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "label_col": [
                    "date",
                ],
                "label": "Total",
                "df": DependsOn("summarize_predation_events"),
            }
            | (params_dict.get("add_predation_summary_row") or {}),
            method="call",
        ),
        "persist_predation_summary": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_predation_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "csv",
                "df": DependsOn("add_predation_summary_row"),
                "filename": "total_livestock_predation_summary_table",
            }
            | (params_dict.get("persist_predation_summary") or {}),
            method="call",
        ),
        "apply_livestock_colormap": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("apply_livestock_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "input_column_name": "Livestock Species",
                "output_column_name": "colors",
                "colormap": "Set3",
                "df": DependsOn("map_livestock_predation"),
            }
            | (params_dict.get("apply_livestock_colormap") or {}),
            method="call",
        ),
        "generate_livestock_layers": Node(
            async_task=create_scatterplot_layer.validate()
            .set_task_instance_id("generate_livestock_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {
                    "get_fill_color": "colors",
                    "get_line_color": "colors",
                    "get_radius": 3,
                    "opacity": 0.55,
                    "stroked": True,
                },
                "legend": {
                    "title": "Livestock Species",
                    "label_column": "Livestock Species",
                    "color_column": "colors",
                    "sort": "ascending",
                    "label_suffix": None,
                },
                "data_url": None,
                "geodataframe": DependsOn("apply_livestock_colormap"),
            }
            | (params_dict.get("generate_livestock_layers") or {}),
            method="call",
        ),
        "combine_custom_livestock": Node(
            async_task=combine_deckgl_map_layers.validate()
            .set_task_instance_id("combine_custom_livestock")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "static_layers": [
                    DependsOn("create_conservancy_boundaries"),
                    DependsOn("create_mnc_parcels_layers"),
                    DependsOn("conservancy_text_layer"),
                ],
                "grouped_layers": DependsOn("generate_livestock_layers"),
            }
            | (params_dict.get("combine_custom_livestock") or {}),
            method="call",
        ),
        "draw_livestock_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("draw_livestock_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("configure_base_maps"),
                "static": False,
                "title": None,
                "max_zoom": 10,
                "legend_style": {
                    "placement": "bottom-right",
                },
                "geo_layers": DependsOn("combine_custom_livestock"),
                "view_state": {
                    "longitude": 35.2092935880001,
                    "latitude": -1.257840580999955,
                    "zoom": 9.75,
                    "pitch": 0,
                    "bearing": 0,
                },
            }
            | (params_dict.get("draw_livestock_map") or {}),
            method="call",
        ),
        "persist_livestock_urls": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_livestock_urls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("draw_livestock_map"),
                "filename": "livestock_predation_events.html",
            }
            | (params_dict.get("persist_livestock_urls") or {}),
            method="call",
        ),
        "convert_livestock_png": Node(
            async_task=html_to_png.validate()
            .set_task_instance_id("convert_livestock_png")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "html_path": DependsOn("persist_livestock_urls"),
                "config": {
                    "full_page": False,
                    "device_scale_factor": 2.0,
                    "wait_for_timeout": 40000,
                    "max_concurrent_pages": 1,
                },
            }
            | (params_dict.get("convert_livestock_png") or {}),
            method="call",
        ),
        "map_livestock_summary": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("map_livestock_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("map_livestock_predation"),
                "retain_columns": [
                    "date",
                    "Livestock Species",
                    "Suspected Predator",
                    "Total livestock affected",
                ],
                "rename_columns": {
                    "Livestock Species": "livestock_species",
                    "Suspected Predator": "suspected_predator",
                    "Total livestock affected": "total_livestock_affected",
                },
                "raise_if_not_found": False,
            }
            | (params_dict.get("map_livestock_summary") or {}),
            method="call",
        ),
        "replace_livestock_nulls": Node(
            async_task=replace_empty_strings_in_columns.validate()
            .set_task_instance_id("replace_livestock_nulls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("map_livestock_summary"),
                "columns": [
                    "suspected_predator",
                    "livestock_species",
                ],
                "replacement": "Unknown",
                "strip_whitespace": False,
                "missing": "ignore",
            }
            | (params_dict.get("replace_livestock_nulls") or {}),
            method="call",
        ),
        "map_livestock_unknown": Node(
            async_task=map_column_values.validate()
            .set_task_instance_id("map_livestock_unknown")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("replace_livestock_nulls"),
                "columns": [
                    "suspected_predator",
                ],
                "value_map": {
                    "Other (specify in comments)": "Unknown",
                },
                "inplace": True,
            }
            | (params_dict.get("map_livestock_unknown") or {}),
            method="call",
        ),
        "convert_livestock_int": Node(
            async_task=coerce_columns_to_int.validate()
            .set_task_instance_id("convert_livestock_int")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("map_livestock_unknown"),
                "columns": [
                    "total_livestock_affected",
                ],
                "errors": "coerce",
                "fill_value": 0,
                "missing": "ignore",
                "nullable": True,
            }
            | (params_dict.get("convert_livestock_int") or {}),
            method="call",
        ),
        "persist_livestock_summary": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_livestock_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "csv",
                "filename": "livestock_predation_summary_table",
                "df": DependsOn("convert_livestock_int"),
            }
            | (params_dict.get("persist_livestock_summary") or {}),
            method="call",
        ),
        "map_illegal_grazing": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("map_illegal_grazing")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("drop_illegal_prefix"),
                "retain_columns": [
                    "date",
                    "event_type",
                    "geometry",
                    "Herd Zone",
                    "Landowner name",
                    "action taken",
                ],
                "raise_if_not_found": False,
            }
            | (params_dict.get("map_illegal_grazing") or {}),
            method="call",
        ),
        "generate_illegal_layers": Node(
            async_task=create_scatterplot_layer.validate()
            .set_task_instance_id("generate_illegal_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {
                    "get_fill_color": [
                        0,
                        0,
                        128,
                    ],
                    "get_line_color": [
                        0,
                        0,
                        128,
                    ],
                    "get_radius": 3,
                    "opacity": 0.55,
                    "stroked": True,
                },
                "legend": {
                    "title": "Illegal grazing",
                    "values": [
                        {
                            "label": "Illegal grazing",
                            "color": "#000080",
                        },
                    ],
                    "sort": None,
                    "label_suffix": None,
                },
                "data_url": None,
                "geodataframe": DependsOn("map_illegal_grazing"),
            }
            | (params_dict.get("generate_illegal_layers") or {}),
            method="call",
        ),
        "combine_custom_illegal": Node(
            async_task=combine_deckgl_map_layers.validate()
            .set_task_instance_id("combine_custom_illegal")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "static_layers": [
                    DependsOn("create_mnc_styled_layers"),
                    DependsOn("conservancy_text_layer"),
                ],
                "grouped_layers": DependsOn("generate_illegal_layers"),
            }
            | (params_dict.get("combine_custom_illegal") or {}),
            method="call",
        ),
        "draw_illegal_grazing": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("draw_illegal_grazing")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("configure_base_maps"),
                "static": False,
                "title": None,
                "max_zoom": 10,
                "legend_style": {
                    "placement": "bottom-right",
                },
                "geo_layers": DependsOn("combine_custom_illegal"),
                "view_state": DependsOn("global_zoom_value"),
            }
            | (params_dict.get("draw_illegal_grazing") or {}),
            method="call",
        ),
        "persist_illegal_urls": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_illegal_urls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("draw_illegal_grazing"),
                "filename": "illegal_grazing_map.html",
            }
            | (params_dict.get("persist_illegal_urls") or {}),
            method="call",
        ),
        "convert_illegal_png": Node(
            async_task=html_to_png.validate()
            .set_task_instance_id("convert_illegal_png")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "html_path": DependsOn("persist_illegal_urls"),
                "config": {
                    "full_page": False,
                    "device_scale_factor": 2.0,
                    "wait_for_timeout": 40000,
                    "max_concurrent_pages": 1,
                },
            }
            | (params_dict.get("convert_illegal_png") or {}),
            method="call",
        ),
        "mnc_events_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("mnc_events_dashboard")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "time_range": DependsOn("time_range"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("mnc_events_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
