# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_mnc.tasks import (
    create_gdf_from_dict as create_gdf_from_dict,
)
from ecoscope_workflows_ext_ste.tasks import (
    annotate_gdf_dict_with_geom_type as annotate_gdf_dict_with_geom_type,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_custom_text_layer as create_custom_text_layer,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layer_from_gdf as create_deckgl_layer_from_gdf,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layers_from_gdf_dict as create_deckgl_layers_from_gdf_dict,
)
from ecoscope_workflows_ext_ste.tasks import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from ecoscope_workflows_ext_ste.tasks import get_gdf_geom_type as get_gdf_geom_type
from ecoscope_workflows_ext_ste.tasks import split_gdf_by_column as split_gdf_by_column

get_events = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_null_geometry as drop_null_geometry,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_mnc.tasks import add_totals_row as add_totals_row
from ecoscope_workflows_ext_mnc.tasks import convert_to_int as convert_to_int
from ecoscope_workflows_ext_mnc.tasks import (
    exclude_geom_outliers as exclude_geom_outliers,
)
from ecoscope_workflows_ext_mnc.tasks import filter_columns as filter_columns
from ecoscope_workflows_ext_mnc.tasks import map_column_values as map_column_values
from ecoscope_workflows_ext_mnc.tasks import (
    replace_missing_with_label as replace_missing_with_label,
)
from ecoscope_workflows_ext_mnc.tasks import to_sentence_case as to_sentence_case
from ecoscope_workflows_ext_mnc.tasks import transform_columns as transform_columns
from ecoscope_workflows_ext_ste.tasks import (
    combine_deckgl_map_layers as combine_deckgl_map_layers,
)
from ecoscope_workflows_ext_ste.tasks import view_state_deck_gdf as view_state_deck_gdf

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("time_range") or {}))
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .partial(groupers=[], **(params_dict.get("groupers") or {}))
        .call()
    )

    er_client_name = (
        set_er_connection.validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    configure_base_maps = (
        set_base_maps_pydeck.validate()
        .set_task_instance_id("configure_base_maps")
        .handle_errors()
        .with_tracing()
        .partial(
            base_maps=[
                {
                    "url": "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
                    "opacity": 1,
                    "max_zoom": 20,
                }
            ],
            **(params_dict.get("configure_base_maps") or {}),
        )
        .call()
    )

    persist_mnc_gpkg = (
        fetch_and_persist_file.validate()
        .set_task_instance_id("persist_mnc_gpkg")
        .handle_errors()
        .with_tracing()
        .partial(
            url="https://www.dropbox.com/scl/fi/14rcy4lkwp7xgewj3xf7k/mnc_conservancy.gpkg?rlkey=mtqo7ivxrnvjonm2z1zez6h6f&st=gtdi4vv0&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params_dict.get("persist_mnc_gpkg") or {}),
        )
        .call()
    )

    download_mnc_parcels = (
        fetch_and_persist_file.validate()
        .set_task_instance_id("download_mnc_parcels")
        .handle_errors()
        .with_tracing()
        .partial(
            url="https://www.dropbox.com/scl/fi/33rdzy896rh91gtkfs2j3/mnc_across_the_river_parcels.gpkg?rlkey=xima1v0rozc0h9h78esfogx6q&st=o3gkk5p1&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params_dict.get("download_mnc_parcels") or {}),
        )
        .call()
    )

    load_comm_shp = (
        load_df.validate()
        .set_task_instance_id("load_comm_shp")
        .handle_errors()
        .with_tracing()
        .partial(
            file_path=persist_mnc_gpkg,
            layer=None,
            deserialize_json=False,
            **(params_dict.get("load_comm_shp") or {}),
        )
        .call()
    )

    split_gdf_by_zone = (
        split_gdf_by_column.validate()
        .set_task_instance_id("split_gdf_by_zone")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf=load_comm_shp,
            column="grazing_zone",
            **(params_dict.get("split_gdf_by_zone") or {}),
        )
        .call()
    )

    annotate_comm_gdf_dict = (
        annotate_gdf_dict_with_geom_type.validate()
        .set_task_instance_id("annotate_comm_gdf_dict")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf_dict=split_gdf_by_zone,
            **(params_dict.get("annotate_comm_gdf_dict") or {}),
        )
        .call()
    )

    create_mnc_styled_layers = (
        create_deckgl_layers_from_gdf_dict.validate()
        .set_task_instance_id("create_mnc_styled_layers")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf_dict=annotate_comm_gdf_dict,
            styles={
                "Conservancy": {
                    "extruded": False,
                    "get_fill_color": [169, 169, 169],
                    "get_line_color": [169, 169, 169],
                    "get_line_width": 4.0,
                    "stroked": True,
                    "filled": False,
                    "opacity": 0.95,
                },
                "Conservancy Herd Zone": {
                    "extruded": False,
                    "get_fill_color": [173, 255, 47],
                    "get_line_color": [173, 255, 47],
                    "get_line_width": 1.95,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.15,
                },
                "Grazing Zone 1": {
                    "extruded": False,
                    "get_fill_color": [85, 107, 47],
                    "get_line_color": [85, 107, 47],
                    "get_line_width": 1.95,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.15,
                },
                "Grazing Zone 2": {
                    "extruded": False,
                    "get_fill_color": [0, 139, 139],
                    "get_line_color": [0, 139, 139],
                    "get_line_width": 1.95,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.15,
                },
                "Grazing Zone 3": {
                    "extruded": False,
                    "get_fill_color": [0, 100, 0],
                    "get_line_color": [0, 100, 0],
                    "get_line_width": 1.95,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.15,
                },
                "Grazing Zone 4": {
                    "extruded": False,
                    "get_fill_color": [143, 188, 139],
                    "get_line_color": [143, 188, 139],
                    "get_line_width": 1.95,
                    "stroked": True,
                    "filled": True,
                    "opacity": 0.15,
                },
            },
            legends={
                "title": "Legend",
                "values": [
                    {"label": "Conservancy", "color": "#a9a9a9"},
                    {"label": "Conservancy Herd Zone", "color": "#adff2f"},
                    {"label": "Grazing Zone 1", "color": "#556b2f"},
                    {"label": "Grazing Zone 2", "color": "#008b8b"},
                    {"label": "Grazing Zone 3", "color": "#006400"},
                    {"label": "Grazing Zone 4", "color": "#8fbc8b"},
                ],
            },
            **(params_dict.get("create_mnc_styled_layers") or {}),
        )
        .call()
    )

    create_conservancy_boundaries = (
        create_deckgl_layers_from_gdf_dict.validate()
        .set_task_instance_id("create_conservancy_boundaries")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf_dict=annotate_comm_gdf_dict,
            styles={
                "Conservancy": {
                    "extruded": False,
                    "get_fill_color": [169, 169, 169],
                    "get_line_color": [169, 169, 169],
                    "get_line_width": 4.0,
                    "stroked": True,
                    "filled": False,
                    "opacity": 0.95,
                }
            },
            legends={
                "title": "Legend",
                "values": [{"label": "Boundaries", "color": "#a9a9a9"}],
            },
            **(params_dict.get("create_conservancy_boundaries") or {}),
        )
        .call()
    )

    conservancy_gdf = (
        create_gdf_from_dict.validate()
        .set_task_instance_id("conservancy_gdf")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf_dict=split_gdf_by_zone,
            key="Conservancy",
            **(params_dict.get("conservancy_gdf") or {}),
        )
        .call()
    )

    overall_grazing_zones = (
        filter_df.validate()
        .set_task_instance_id("overall_grazing_zones")
        .handle_errors()
        .with_tracing()
        .partial(
            column_name="grazing_zone",
            op="ne",
            value="Conservancy",
            df=load_comm_shp,
            reset_index=False,
            **(params_dict.get("overall_grazing_zones") or {}),
        )
        .call()
    )

    conservancy_text_layer = (
        create_custom_text_layer.validate()
        .set_task_instance_id("conservancy_text_layer")
        .handle_errors()
        .with_tracing()
        .partial(
            geodataframe=conservancy_gdf,
            layer_style={
                "get_text": "name",
                "get_color": [0, 0, 0, 255],
                "get_size": 1500,
                "size_units": "meters",
                "size_min_pixels": 70,
                "size_max_pixels": 100,
                "size_scale": 2.25,
                "font_family": "Calibri",
                "font_weight": "700",
                "get_text_anchor": "middle",
                "get_alignment_baseline": "center",
                "billboard": True,
                "background_padding": [4, 8],
                "pickable": True,
                "auto_highlight": False,
            },
            use_centroid=True,
            legend=None,
            **(params_dict.get("conservancy_text_layer") or {}),
        )
        .call()
    )

    load_mnc_parcels = (
        load_df.validate()
        .set_task_instance_id("load_mnc_parcels")
        .handle_errors()
        .with_tracing()
        .partial(
            file_path=download_mnc_parcels,
            layer=None,
            deserialize_json=False,
            **(params_dict.get("load_mnc_parcels") or {}),
        )
        .call()
    )

    assign_mnc_geom = (
        get_gdf_geom_type.validate()
        .set_task_instance_id("assign_mnc_geom")
        .handle_errors()
        .with_tracing()
        .partial(gdf=load_mnc_parcels, **(params_dict.get("assign_mnc_geom") or {}))
        .call()
    )

    create_mnc_parcels_layers = (
        create_deckgl_layer_from_gdf.validate()
        .set_task_instance_id("create_mnc_parcels_layers")
        .handle_errors()
        .with_tracing()
        .partial(
            gdf=assign_mnc_geom,
            style={
                "extruded": False,
                "get_fill_color": [189, 183, 107],
                "get_line_color": [189, 183, 107],
                "get_line_width": 1.95,
                "stroked": True,
                "filled": True,
                "opacity": 0.15,
            },
            legend={"title": "", "values": [{"label": "Parcels", "color": "#bdb76b"}]},
            **(params_dict.get("create_mnc_parcels_layers") or {}),
        )
        .call()
    )

    get_events_data = (
        get_events.validate()
        .set_task_instance_id("get_events_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "reported_by",
                "serial_number",
                "geometry",
                "created_at",
                "event_details",
                "patrols",
            ],
            event_types=[],
            raise_on_empty=True,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            include_null_geometry=False,
            include_display_values=False,
            **(params_dict.get("get_events_data") or {}),
        )
        .call()
    )

    extract_event_date = (
        extract_column_as_type.validate()
        .set_task_instance_id("extract_event_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_events_data,
            column_name="time",
            output_type="date",
            output_column_name="date",
            **(params_dict.get("extract_event_date") or {}),
        )
        .call()
    )

    events_temporal = (
        add_temporal_index.validate()
        .set_task_instance_id("events_temporal")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_event_date,
            time_col="date",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params_dict.get("events_temporal") or {}),
        )
        .call()
    )

    filter_mobile_boma = (
        filter_df.validate()
        .set_task_instance_id("filter_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="mobile_boma_rep",
            df=events_temporal,
            reset_index=False,
            **(params_dict.get("filter_mobile_boma") or {}),
        )
        .call()
    )

    filter_cattle_count = (
        filter_df.validate()
        .set_task_instance_id("filter_cattle_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="cattle_count",
            df=events_temporal,
            reset_index=False,
            **(params_dict.get("filter_cattle_count") or {}),
        )
        .call()
    )

    normalize_mb_values = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_mb_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=filter_mobile_boma,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_mb_values") or {}),
        )
        .call()
    )

    normalize_cc_values = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_cc_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=filter_cattle_count,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_cc_values") or {}),
        )
        .call()
    )

    rename_mobile_boma = (
        transform_columns.validate()
        .set_task_instance_id("rename_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={"event_details__mobile_boma": "boma"},
            skip_missing_rename=True,
            required_columns=["event_details__mobile_boma"],
            df=normalize_mb_values,
            **(params_dict.get("rename_mobile_boma") or {}),
        )
        .call()
    )

    rename_cattle_count = (
        transform_columns.validate()
        .set_task_instance_id("rename_cattle_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "event_details__cattle_in_zone_4": "zone_4",
                "event_details__cattle_in_zone_1_outside_mobile_boma": "zone_1",
                "event_details__cattle_in_zone_23_outside_mobile_boma": "zone_2_3",
                "event_details__total_cattle_counted_from_all_zones": "total_count",
            },
            skip_missing_rename=True,
            required_columns=["event_details__total_cattle_counted_from_all_zones"],
            df=normalize_cc_values,
            **(params_dict.get("rename_cattle_count") or {}),
        )
        .call()
    )

    rename_boma_values = (
        map_column_values.validate()
        .set_task_instance_id("rename_boma_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_mobile_boma,
            columns=["event_type"],
            value_map={"mobile_boma_rep": "Mobile boma"},
            inplace=False,
            **(params_dict.get("rename_boma_values") or {}),
        )
        .call()
    )

    calculate_total_boma = (
        summarize_df.validate()
        .set_task_instance_id("calculate_total_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["date"],
            summary_params=[
                {"display_name": "total_count", "aggregator": "nunique", "column": "id"}
            ],
            reset_index=True,
            df=rename_boma_values,
            **(params_dict.get("calculate_total_boma") or {}),
        )
        .call()
    )

    add_total_boma_row = (
        add_totals_row.validate()
        .set_task_instance_id("add_total_boma_row")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            label_col=["date"],
            label="Total",
            df=calculate_total_boma,
            **(params_dict.get("add_total_boma_row") or {}),
        )
        .call()
    )

    persist_boma_count_df = (
        persist_df.validate()
        .set_task_instance_id("persist_boma_count_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=add_total_boma_row,
            filename="total_boma_count_by_date",
            **(params_dict.get("persist_boma_count_df") or {}),
        )
        .call()
    )

    filter_cattle_cols = (
        filter_columns.validate()
        .set_task_instance_id("filter_cattle_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_cattle_count,
            columns=["date", "zone_1", "zone_2_3", "zone_4", "total_count"],
            exclude=[],
            **(params_dict.get("filter_cattle_cols") or {}),
        )
        .call()
    )

    persist_cattle_count_df = (
        persist_df.validate()
        .set_task_instance_id("persist_cattle_count_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            filename="mobile_boma_summary_table",
            df=filter_cattle_cols,
            **(params_dict.get("persist_cattle_count_df") or {}),
        )
        .call()
    )

    exclude_mb_outliers = (
        exclude_geom_outliers.validate()
        .set_task_instance_id("exclude_mb_outliers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_boma_values,
            z_threshold=3,
            **(params_dict.get("exclude_mb_outliers") or {}),
        )
        .call()
    )

    remove_mb_invalid_geoms = (
        drop_null_geometry.validate()
        .set_task_instance_id("remove_mb_invalid_geoms")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=exclude_mb_outliers,
            geometry_column="geometry",
            **(params_dict.get("remove_mb_invalid_geoms") or {}),
        )
        .call()
    )

    apply_mb_colormap = (
        apply_color_map.validate()
        .set_task_instance_id("apply_mb_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="event_type",
            output_column_name="event_type_colors",
            colormap="tab20",
            df=remove_mb_invalid_geoms,
            **(params_dict.get("apply_mb_colormap") or {}),
        )
        .call()
    )

    generate_mb_layers = (
        create_scatterplot_layer.validate()
        .set_task_instance_id("generate_mb_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_fill_color": "event_type_colors",
                "get_line_color": "event_type_colors",
                "get_radius": 4,
                "opacity": 0.75,
                "stroked": True,
            },
            legend={
                "title": "Boma Movements",
                "label_column": "event_type",
                "color_column": "event_type_colors",
                "sort": "ascending",
                "label_suffix": None,
            },
            geodataframe=apply_mb_colormap,
            **(params_dict.get("generate_mb_layers") or {}),
        )
        .call()
    )

    global_zoom_value = (
        view_state_deck_gdf.validate()
        .set_task_instance_id("global_zoom_value")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            pitch=0,
            bearing=0,
            gdf=overall_grazing_zones,
            **(params_dict.get("global_zoom_value") or {}),
        )
        .call()
    )

    combine_custom_mobile_boma = (
        combine_deckgl_map_layers.validate()
        .set_task_instance_id("combine_custom_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[
                create_mnc_styled_layers,
                create_mnc_parcels_layers,
                conservancy_text_layer,
            ],
            grouped_layers=generate_mb_layers,
            **(params_dict.get("combine_custom_mobile_boma") or {}),
        )
        .call()
    )

    draw_mb_map = (
        draw_map.validate()
        .set_task_instance_id("draw_mb_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=combine_custom_mobile_boma,
            view_state=global_zoom_value,
            **(params_dict.get("draw_mb_map") or {}),
        )
        .call()
    )

    persist_mobile_boma_urls = (
        persist_text.validate()
        .set_task_instance_id("persist_mobile_boma_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_mb_map,
            filename="boma_movement_map.html",
            **(params_dict.get("persist_mobile_boma_urls") or {}),
        )
        .call()
    )

    filter_predation = (
        filter_df.validate()
        .set_task_instance_id("filter_predation")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="livestock_predation_rep",
            df=events_temporal,
            reset_index=False,
            **(params_dict.get("filter_predation") or {}),
        )
        .call()
    )

    normalize_predation_values = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_predation_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=filter_predation,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_predation_values") or {}),
        )
        .call()
    )

    rename_livestock_predation = (
        transform_columns.validate()
        .set_task_instance_id("rename_livestock_predation")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "event_details__livestockpredation_comments": "livestock_predation_comments",
                "event_details__livestockpredation_location": "predation_location",
                "event_details__livestockpredation_causedeath": "predation_cause_of_death",
                "event_details__livestockpredation_retaliation": "predation_retaliation",
                "event_details__livestockpredation_supervision": "predation_supervision",
                "event_details__livestockpredation_predatorcount": "predator_count",
                "event_details__livestockpredation_killedjuvenile": "killed_juvenile",
                "event_details__livestockpredation_livestockowner": "livestock_owner",
                "event_details__livestockpredation_distancetopeople": "distance_to_people",
                "event_details__livestockpredation_livestockspecies": "livestock_species",
                "event_details__livestockpredation_livestockaffected": "livestock_affected",
                "event_details__livestockpredation_suspectedpredator": "suspected_predator",
                "event_details__livestockpredation_bomacontext": "boma_context",
                "event_details__livestockpredation_killedadultmale": "killed_adult_male",
                "event_details__livestockpredation_bomaconstruction": "boma_construction",
                "event_details__livestockpredation_woundedjuvenile": "wounded_juvenile",
                "event_details__livestockpredation_woundedadultfemale": "wounded_adult_female",
                "event_details__livestockpredation_woundedadultmale": "wounded_adult_male",
                "event_details__livestockpredation_bomaheight": "boma_height",
                "event_details__livestockpredation_bomavisibility": "boma_visibility",
            },
            skip_missing_rename=True,
            required_columns=[
                "event_details__livestockpredation_livestockaffected",
                "event_details__livestockpredation_livestockspecies",
                "event_details__livestockpredation_suspectedpredator",
            ],
            df=normalize_predation_values,
            **(params_dict.get("rename_livestock_predation") or {}),
        )
        .call()
    )

    replace_livestock_nulls = (
        replace_missing_with_label.validate()
        .set_task_instance_id("replace_livestock_nulls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_livestock_predation,
            columns=["suspected_predator", "livestock_species"],
            label="unknown",
            **(params_dict.get("replace_livestock_nulls") or {}),
        )
        .call()
    )

    convert_livestock_int = (
        convert_to_int.validate()
        .set_task_instance_id("convert_livestock_int")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=replace_livestock_nulls,
            columns=["livestock_affected"],
            errors="coerce",
            fill_value=0,
            inplace=False,
            **(params_dict.get("convert_livestock_int") or {}),
        )
        .call()
    )

    livestock_preds_scase = (
        to_sentence_case.validate()
        .set_task_instance_id("livestock_preds_scase")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_livestock_int,
            columns=["suspected_predator", "livestock_species"],
            **(params_dict.get("livestock_preds_scase") or {}),
        )
        .call()
    )

    persist_livestock_events_gpkg = (
        persist_df.validate()
        .set_task_instance_id("persist_livestock_events_gpkg")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="gpkg",
            filename="livestock_predation_events",
            df=livestock_preds_scase,
            **(params_dict.get("persist_livestock_events_gpkg") or {}),
        )
        .call()
    )

    persist_livestock_events_csv = (
        persist_df.validate()
        .set_task_instance_id("persist_livestock_events_csv")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            filename="livestock_predation_events",
            df=livestock_preds_scase,
            **(params_dict.get("persist_livestock_events_csv") or {}),
        )
        .call()
    )

    livestock_predation_summary = (
        summarize_df.validate()
        .set_task_instance_id("livestock_predation_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["date", "suspected_predator", "livestock_species"],
            summary_params=[
                {
                    "display_name": "no_affected",
                    "aggregator": "sum",
                    "column": "livestock_affected",
                }
            ],
            reset_index=True,
            df=livestock_preds_scase,
            **(params_dict.get("livestock_predation_summary") or {}),
        )
        .call()
    )

    persist_livestock_df = (
        persist_df.validate()
        .set_task_instance_id("persist_livestock_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            filename="livestock_predation_summary_table",
            df=livestock_predation_summary,
            **(params_dict.get("persist_livestock_df") or {}),
        )
        .call()
    )

    livestock_events_recorded = (
        summarize_df.validate()
        .set_task_instance_id("livestock_events_recorded")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["date"],
            summary_params=[
                {
                    "display_name": "no_of_events",
                    "aggregator": "nunique",
                    "column": "id",
                }
            ],
            reset_index=True,
            df=livestock_preds_scase,
            **(params_dict.get("livestock_events_recorded") or {}),
        )
        .call()
    )

    add_total_livestock = (
        add_totals_row.validate()
        .set_task_instance_id("add_total_livestock")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            label_col=["date"],
            label="Total",
            df=livestock_events_recorded,
            **(params_dict.get("add_total_livestock") or {}),
        )
        .call()
    )

    livestock_events_df = (
        persist_df.validate()
        .set_task_instance_id("livestock_events_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=add_total_livestock,
            filename="livestock_events_recorded_by_date",
            **(params_dict.get("livestock_events_df") or {}),
        )
        .call()
    )

    exclude_livestock_outliers = (
        exclude_geom_outliers.validate()
        .set_task_instance_id("exclude_livestock_outliers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=livestock_preds_scase,
            z_threshold=3,
            **(params_dict.get("exclude_livestock_outliers") or {}),
        )
        .call()
    )

    remove_livestock_invalid_geoms = (
        drop_null_geometry.validate()
        .set_task_instance_id("remove_livestock_invalid_geoms")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=exclude_livestock_outliers,
            geometry_column="geometry",
            **(params_dict.get("remove_livestock_invalid_geoms") or {}),
        )
        .call()
    )

    apply_livestock_colormap = (
        apply_color_map.validate()
        .set_task_instance_id("apply_livestock_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="livestock_species",
            output_column_name="colors",
            colormap="tab20",
            df=remove_livestock_invalid_geoms,
            **(params_dict.get("apply_livestock_colormap") or {}),
        )
        .call()
    )

    generate_livestock_layers = (
        create_scatterplot_layer.validate()
        .set_task_instance_id("generate_livestock_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_fill_color": "colors",
                "get_line_color": "colors",
                "get_radius": 4,
                "opacity": 0.75,
                "stroked": True,
            },
            legend={
                "title": "Livestock Species",
                "label_column": "livestock_species",
                "color_column": "colors",
                "sort": "ascending",
                "label_suffix": None,
            },
            geodataframe=apply_livestock_colormap,
            **(params_dict.get("generate_livestock_layers") or {}),
        )
        .call()
    )

    combine_custom_livestock = (
        combine_deckgl_map_layers.validate()
        .set_task_instance_id("combine_custom_livestock")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[
                create_conservancy_boundaries,
                create_mnc_parcels_layers,
                conservancy_text_layer,
            ],
            grouped_layers=generate_livestock_layers,
            **(params_dict.get("combine_custom_livestock") or {}),
        )
        .call()
    )

    draw_livestock_map = (
        draw_map.validate()
        .set_task_instance_id("draw_livestock_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=combine_custom_livestock,
            view_state={
                "longitude": 35.2092935880001,
                "latitude": -1.257840580999955,
                "zoom": 9.75,
                "pitch": 0,
                "bearing": 0,
            },
            **(params_dict.get("draw_livestock_map") or {}),
        )
        .call()
    )

    persist_livestock_urls = (
        persist_text.validate()
        .set_task_instance_id("persist_livestock_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_livestock_map,
            filename="livestock_predation_events.html",
            **(params_dict.get("persist_livestock_urls") or {}),
        )
        .call()
    )

    convert_mobile_boma_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_mobile_boma_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_mobile_boma_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_mobile_boma_png") or {}),
        )
        .call()
    )

    convert_livestock_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_livestock_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_livestock_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_livestock_png") or {}),
        )
        .call()
    )

    mnc_events_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("mnc_events_dashboard")
        .handle_errors()
        .with_tracing()
        .partial(
            details=workflow_details,
            widgets=[],
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("mnc_events_dashboard") or {}),
        )
        .call()
    )

    return mnc_events_dashboard
