# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.results import (
    create_geojson_layer as create_geojson_layer_1,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_mnc.tasks.transformation import (
    build_legend_values_from_column as build_legend_values_from_column,
)
from ecoscope_workflows_ext_mnc.tasks.transformation import (
    fix_invalid_geometries as fix_invalid_geometries,
)
from ecoscope_workflows_ext_ste.tasks.io import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_events = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.io import persist_df as persist_df
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.transformation import (
    convert_column_values_to_numeric as convert_column_values_to_numeric,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer_1,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map_1
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_null_geometry as drop_null_geometry_1,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    format_text_column as format_text_column,
)
from ecoscope_workflows_ext_mnc.tasks.aggregation import (
    apply_arithmetic_operation_over_rows as apply_arithmetic_operation_over_rows_1,
)
from ecoscope_workflows_ext_mnc.tasks.transformation import (
    convert_columns_to_int as convert_columns_to_int,
)
from ecoscope_workflows_ext_mnc.tasks.transformation import (
    fill_missing_values as fill_missing_values,
)
from ecoscope_workflows_ext_mnc.tasks.transformation import (
    replace_column_values as replace_column_values,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    combine_deckgl_map_layers as combine_deckgl_map_layers,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    compute_view_state_from_gdf as compute_view_state_from_gdf,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    envelope_gdf as envelope_gdf,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("time_range") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params.get("groupers") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    configure_base_maps = (
        task(set_base_maps_pydeck)
        .validate()
        .set_task_instance_id("configure_base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            base_maps=[
                {
                    "url": "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
                    "opacity": 0.8,
                    "max_zoom": 20,
                },
                {
                    "url": "https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places_Alternate/MapServer/tile/{z}/{y}/{x}",
                    "opacity": 0.35,
                    "max_zoom": 20,
                },
            ],
            **(params.get("configure_base_maps") or {}),
        )
        .call()
    )

    persist_mnc_gpkg = (
        task(fetch_and_persist_file)
        .validate()
        .set_task_instance_id("persist_mnc_gpkg")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            url="https://www.dropbox.com/scl/fi/14rcy4lkwp7xgewj3xf7k/mnc_conservancy.gpkg?rlkey=mtqo7ivxrnvjonm2z1zez6h6f&st=gtdi4vv0&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params.get("persist_mnc_gpkg") or {}),
        )
        .call()
    )

    download_mnc_parcels = (
        task(fetch_and_persist_file)
        .validate()
        .set_task_instance_id("download_mnc_parcels")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            url="https://www.dropbox.com/scl/fi/33rdzy896rh91gtkfs2j3/mnc_across_the_river_parcels.gpkg?rlkey=xima1v0rozc0h9h78esfogx6q&st=o3gkk5p1&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params.get("download_mnc_parcels") or {}),
        )
        .call()
    )

    load_comm_shp = (
        task(load_df)
        .validate()
        .set_task_instance_id("load_comm_shp")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            file_path=persist_mnc_gpkg,
            layer=None,
            deserialize_json=False,
            **(params.get("load_comm_shp") or {}),
        )
        .call()
    )

    fix_comm_geom = (
        task(fix_invalid_geometries)
        .validate()
        .set_task_instance_id("fix_comm_geom")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(gdf=load_comm_shp, **(params.get("fix_comm_geom") or {}))
        .call()
    )

    filter_conservancy_boundary = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_conservancy_boundary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=fix_comm_geom,
            column_name="grazing_zone",
            op="equal",
            value="Conservancy",
            reset_index=True,
            **(params.get("filter_conservancy_boundary") or {}),
        )
        .call()
    )

    filter_mara_north = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_mara_north")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=fix_comm_geom,
            column_name="name",
            op="equal",
            value="Mara North Conservancy",
            reset_index=True,
            **(params.get("filter_mara_north") or {}),
        )
        .call()
    )

    filter_grazing_zones = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_grazing_zones")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=fix_comm_geom,
            column_name="grazing_zone",
            op="ne",
            value="Conservancy",
            reset_index=True,
            **(params.get("filter_grazing_zones") or {}),
        )
        .call()
    )

    color_grazing_zones = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("color_grazing_zones")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_grazing_zones,
            input_column_name="grazing_zone",
            output_column_name="zone_color",
            colormap="GnBu",
            **(params.get("color_grazing_zones") or {}),
        )
        .call()
    )

    grazing_zone_legend_values = (
        task(build_legend_values_from_column)
        .validate()
        .set_task_instance_id("grazing_zone_legend_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=color_grazing_zones,
            label_column="grazing_zone",
            color_column="zone_color",
            sort="ascending",
            **(params.get("grazing_zone_legend_values") or {}),
        )
        .call()
    )

    load_mnc_parcels = (
        task(load_df)
        .validate()
        .set_task_instance_id("load_mnc_parcels")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            file_path=download_mnc_parcels,
            layer=None,
            deserialize_json=False,
            **(params.get("load_mnc_parcels") or {}),
        )
        .call()
    )

    create_conservancy_layer = (
        task(create_geojson_layer_1)
        .validate()
        .set_task_instance_id("create_conservancy_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=filter_conservancy_boundary,
            data_url=None,
            layer_style={
                "filled": False,
                "stroked": True,
                "get_line_color": [169, 169, 169, 255],
                "get_line_width": 1.75,
            },
            legend={
                "title": "",
                "values": [{"label": "Conservancy Boundary", "color": "#a9a9a9"}],
                "sort": None,
                "label_suffix": None,
            },
            **(params.get("create_conservancy_layer") or {}),
        )
        .call()
    )

    create_grazing_zones_layer = (
        task(create_geojson_layer_1)
        .validate()
        .set_task_instance_id("create_grazing_zones_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=color_grazing_zones,
            data_url=None,
            layer_style={
                "filled": True,
                "stroked": True,
                "opacity": 0.5,
                "get_fill_color": "zone_color",
                "get_line_color": "zone_color",
                "get_line_width": 1.5,
            },
            legend={"title": "Map Layers", "values": grazing_zone_legend_values},
            **(params.get("create_grazing_zones_layer") or {}),
        )
        .call()
    )

    create_parcels_layer = (
        task(create_geojson_layer_1)
        .validate()
        .set_task_instance_id("create_parcels_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=load_mnc_parcels,
            data_url=None,
            layer_style={
                "filled": True,
                "stroked": True,
                "get_fill_color": [189, 183, 107, 60],
                "get_line_color": [189, 183, 107, 255],
                "get_line_width": 1.5,
            },
            legend={
                "title": "",
                "values": [{"label": "Parcels", "color": "#bdb76b"}],
                "sort": None,
                "label_suffix": None,
            },
            **(params.get("create_parcels_layer") or {}),
        )
        .call()
    )

    get_events_data = (
        task(get_events)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("get_events_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "reported_by",
                "serial_number",
                "geometry",
                "created_at",
                "event_details",
                "patrols",
            ],
            event_types=[
                "mobile_boma_rep",
                "cattle_count",
                "livestock_predation_rep",
                "illegal_grazing_rep",
            ],
            raise_on_empty=True,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            include_null_geometry=False,
            include_display_values=False,
            force_point_geometry=True,
            **(params.get("get_events_data") or {}),
        )
        .call()
    )

    extract_event_date = (
        task(extract_column_as_type)
        .validate()
        .set_task_instance_id("extract_event_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_events_data,
            column_name="time",
            output_type="date",
            output_column_name="date",
            **(params.get("extract_event_date") or {}),
        )
        .call()
    )

    events_temporal = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("events_temporal")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_event_date,
            time_col="date",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("events_temporal") or {}),
        )
        .call()
    )

    filter_mobile_boma = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_temporal,
            column_name="event_type",
            op="equal",
            value="mobile_boma_rep",
            reset_index=True,
            **(params.get("filter_mobile_boma") or {}),
        )
        .call()
    )

    filter_livestock_predation = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_livestock_predation")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_temporal,
            column_name="event_type",
            op="equal",
            value="livestock_predation_rep",
            reset_index=True,
            **(params.get("filter_livestock_predation") or {}),
        )
        .call()
    )

    filter_cattle_counts = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_cattle_counts")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_temporal,
            column_name="event_type",
            op="equal",
            value="cattle_count",
            reset_index=True,
            **(params.get("filter_cattle_counts") or {}),
        )
        .call()
    )

    filter_illegal_grazing = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_illegal_grazing")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_temporal,
            column_name="event_type",
            op="equal",
            value="illegal_grazing_rep",
            reset_index=True,
            **(params.get("filter_illegal_grazing") or {}),
        )
        .call()
    )

    process_mobile_boma = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("process_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_mobile_boma,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("process_mobile_boma") or {}),
        )
        .call()
    )

    normalize_mobile_boma = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_mobile_boma,
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_mobile_boma") or {}),
        )
        .call()
    )

    drop_mobile_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_mobile_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_mobile_boma,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params.get("drop_mobile_prefix") or {}),
        )
        .call()
    )

    process_livestock_preds = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("process_livestock_preds")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_livestock_predation,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("process_livestock_preds") or {}),
        )
        .call()
    )

    normalize_livestock_preds = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_livestock_preds")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_livestock_preds,
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_livestock_preds") or {}),
        )
        .call()
    )

    drop_predation_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_predation_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_livestock_preds,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params.get("drop_predation_prefix") or {}),
        )
        .call()
    )

    process_cattle_counts = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("process_cattle_counts")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_cattle_counts,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("process_cattle_counts") or {}),
        )
        .call()
    )

    normalize_cattle_count = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_cattle_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_cattle_counts,
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_cattle_count") or {}),
        )
        .call()
    )

    drop_cattle_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_cattle_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_cattle_count,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params.get("drop_cattle_prefix") or {}),
        )
        .call()
    )

    process_illegal_grazing = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("process_illegal_grazing")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_illegal_grazing,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("process_illegal_grazing") or {}),
        )
        .call()
    )

    normalize_illegal_grazing = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_illegal_grazing")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_illegal_grazing,
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_illegal_grazing") or {}),
        )
        .call()
    )

    drop_illegal_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_illegal_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_illegal_grazing,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params.get("drop_illegal_prefix") or {}),
        )
        .call()
    )

    map_mobile_boma = (
        task(map_columns)
        .validate()
        .set_task_instance_id("map_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_mobile_prefix,
            drop_columns=[],
            retain_columns=[
                "id",
                "date",
                "event_type",
                "geometry",
                "Date of Relocation",
                "Electric Boma Status",
                "Mobile Boma Zone",
                "Nature of the Site",
                "Reason for relocation",
            ],
            rename_columns={},
            raise_if_not_found=False,
            **(params.get("map_mobile_boma") or {}),
        )
        .call()
    )

    summarize_mobile_boma = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("summarize_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_mobile_boma,
            groupby_cols=["date"],
            summary_params=[
                {
                    "display_name": "boma_events",
                    "aggregator": "nunique",
                    "column": "id",
                    "decimal_places": 0,
                }
            ],
            reset_index=True,
            **(params.get("summarize_mobile_boma") or {}),
        )
        .call()
    )

    persist_boma_summary = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_boma_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=summarize_mobile_boma,
            filename="mobile_boma_movement_summary_table",
            **(params.get("persist_boma_summary") or {}),
        )
        .call()
    )

    drop_null_mobile = (
        task(drop_null_geometry_1)
        .validate()
        .set_task_instance_id("drop_null_mobile")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=map_mobile_boma,
            geometry_column="geometry",
            **(params.get("drop_null_mobile") or {}),
        )
        .call()
    )

    generate_mobile_layers = (
        task(create_scatterplot_layer_1)
        .validate()
        .set_task_instance_id("generate_mobile_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            layer_style={
                "get_fill_color": [0, 0, 128],
                "get_line_color": [0, 0, 128],
                "get_radius": 3,
                "opacity": 0.55,
                "stroked": True,
            },
            legend={
                "title": "Movements",
                "values": [{"label": "Boma movement", "color": "#000080"}],
                "sort": None,
                "label_suffix": None,
            },
            geodataframe=drop_null_mobile,
            **(params.get("generate_mobile_layers") or {}),
        )
        .call()
    )

    zoom_to_envelope = (
        task(envelope_gdf)
        .validate()
        .set_task_instance_id("zoom_to_envelope")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(gdf=filter_mara_north, **(params.get("zoom_to_envelope") or {}))
        .call()
    )

    gdf_image_extent = (
        task(compute_view_state_from_gdf)
        .validate()
        .set_task_instance_id("gdf_image_extent")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            pitch=0,
            bearing=0,
            max_zoom=15,
            gdf=zoom_to_envelope,
            **(params.get("gdf_image_extent") or {}),
        )
        .call()
    )

    combine_custom_mobile_boma = (
        task(combine_deckgl_map_layers)
        .validate()
        .set_task_instance_id("combine_custom_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[
                create_grazing_zones_layer,
                create_parcels_layer,
                create_conservancy_layer,
            ],
            grouped_layers=generate_mobile_layers,
            **(params.get("combine_custom_mobile_boma") or {}),
        )
        .call()
    )

    draw_mobile_boma = (
        task(draw_map_1)
        .validate()
        .set_task_instance_id("draw_mobile_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=combine_custom_mobile_boma,
            view_state=gdf_image_extent,
            **(params.get("draw_mobile_boma") or {}),
        )
        .call()
    )

    persist_mobile_boma_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_mobile_boma_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_mobile_boma,
            filename="boma_movement_map.html",
            filename_suffix=None,
            **(params.get("persist_mobile_boma_urls") or {}),
        )
        .call()
    )

    mobile_boma_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("mobile_boma_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Mobile Boma Movement Map",
            data=persist_mobile_boma_urls,
            **(params.get("mobile_boma_map_widget") or {}),
        )
        .call()
    )

    convert_mobile_boma_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("convert_mobile_boma_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_mobile_boma_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params.get("convert_mobile_boma_png") or {}),
        )
        .call()
    )

    map_cattle_count = (
        task(map_columns)
        .validate()
        .set_task_instance_id("map_cattle_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_cattle_prefix,
            drop_columns=["total_cattle_counted_from_all_zones"],
            retain_columns=[
                "date",
                "# cattle in Zone 1 mobile boma",
                "# cattle in Zone 2/3 mobile boma",
                "# cattle in Zone 4",
            ],
            rename_columns={
                "# cattle in Zone 1 mobile boma": "zone_1",
                "# cattle in Zone 2/3 mobile boma": "zone_2_3",
                "# cattle in Zone 4": "zone_4",
            },
            raise_if_not_found=False,
            **(params.get("map_cattle_count") or {}),
        )
        .call()
    )

    convert_cols_numeric = (
        task(convert_column_values_to_numeric)
        .validate()
        .set_task_instance_id("convert_cols_numeric")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_cattle_count,
            columns=["zone_1", "zone_2_3", "zone_4"],
            **(params.get("convert_cols_numeric") or {}),
        )
        .call()
    )

    compute_total_count = (
        task(apply_arithmetic_operation_over_rows_1)
        .validate()
        .set_task_instance_id("compute_total_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_cols_numeric,
            columns=["zone_1", "zone_2_3", "zone_4"],
            operation="add",
            output_column="total",
            **(params.get("compute_total_count") or {}),
        )
        .call()
    )

    rename_cattle_count_display = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_cattle_count_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=compute_total_count,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "date": "Date",
                "zone_1": "Zone 1",
                "zone_2_3": "Zone 2/3",
                "zone_4": "Zone 4",
                "total": "Total",
            },
            raise_if_not_found=False,
            **(params.get("rename_cattle_count_display") or {}),
        )
        .call()
    )

    persist_cattle_count = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_cattle_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=rename_cattle_count_display,
            filename="total_cattle_count_summary_table",
            **(params.get("persist_cattle_count") or {}),
        )
        .call()
    )

    cattle_count_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("cattle_count_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=rename_cattle_count_display,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Total Cattle Count Summary",
            **(params.get("cattle_count_table_html") or {}),
        )
        .call()
    )

    cattle_count_table_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("cattle_count_table_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=cattle_count_table_html,
            filename="total_cattle_count_summary_table.html",
            filename_suffix=None,
            **(params.get("cattle_count_table_html_url") or {}),
        )
        .call()
    )

    cattle_count_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("cattle_count_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Cattle Count Summary",
            data=cattle_count_table_html_url,
            **(params.get("cattle_count_table_widget") or {}),
        )
        .call()
    )

    map_livestock_predation = (
        task(map_columns)
        .validate()
        .set_task_instance_id("map_livestock_predation")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_predation_prefix,
            drop_columns=[],
            retain_columns=[
                "id",
                "date",
                "event_type",
                "geometry",
                "Livestock Species",
                "Suspected Predator",
                "Total livestock affected",
            ],
            rename_columns={},
            raise_if_not_found=False,
            **(params.get("map_livestock_predation") or {}),
        )
        .call()
    )

    summarize_predation_events = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("summarize_predation_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_livestock_predation,
            groupby_cols=["date"],
            summary_params=[
                {
                    "display_name": "livestock_predation_events",
                    "aggregator": "nunique",
                    "column": "id",
                    "decimal_places": 0,
                }
            ],
            reset_index=True,
            **(params.get("summarize_predation_events") or {}),
        )
        .call()
    )

    rename_predation_summary_display = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_predation_summary_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=summarize_predation_events,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "date": "Date",
                "livestock_predation_events": "Livestock Predation Events",
            },
            raise_if_not_found=False,
            **(params.get("rename_predation_summary_display") or {}),
        )
        .call()
    )

    persist_predation_summary = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_predation_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=rename_predation_summary_display,
            filename="total_livestock_predation_summary_table",
            **(params.get("persist_predation_summary") or {}),
        )
        .call()
    )

    predation_summary_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("predation_summary_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=rename_predation_summary_display,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Livestock Predation Summary",
            **(params.get("predation_summary_table_html") or {}),
        )
        .call()
    )

    predation_summary_table_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("predation_summary_table_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=predation_summary_table_html,
            filename="livestock_predation_summary_table.html",
            filename_suffix=None,
            **(params.get("predation_summary_table_html_url") or {}),
        )
        .call()
    )

    predation_summary_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("predation_summary_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Livestock Predation Summary",
            data=predation_summary_table_html_url,
            **(params.get("predation_summary_table_widget") or {}),
        )
        .call()
    )

    capitalize_livestock_species = (
        task(format_text_column)
        .validate()
        .set_task_instance_id("capitalize_livestock_species")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_livestock_predation,
            column="Livestock Species",
            method="capitalize",
            **(params.get("capitalize_livestock_species") or {}),
        )
        .call()
    )

    apply_livestock_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("apply_livestock_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="Livestock Species",
            output_column_name="colors",
            colormap="tab10",
            df=capitalize_livestock_species,
            **(params.get("apply_livestock_colormap") or {}),
        )
        .call()
    )

    drop_null_livestock = (
        task(drop_null_geometry_1)
        .validate()
        .set_task_instance_id("drop_null_livestock")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=apply_livestock_colormap,
            geometry_column="geometry",
            **(params.get("drop_null_livestock") or {}),
        )
        .call()
    )

    generate_livestock_layers = (
        task(create_scatterplot_layer_1)
        .validate()
        .set_task_instance_id("generate_livestock_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_fill_color": "colors",
                "get_line_color": "colors",
                "get_radius": 3,
                "opacity": 0.55,
                "stroked": True,
            },
            legend={
                "title": "Livestock Species",
                "label_column": "Livestock Species",
                "color_column": "colors",
                "sort": "ascending",
                "label_suffix": None,
            },
            data_url=None,
            geodataframe=drop_null_livestock,
            **(params.get("generate_livestock_layers") or {}),
        )
        .call()
    )

    combine_custom_livestock = (
        task(combine_deckgl_map_layers)
        .validate()
        .set_task_instance_id("combine_custom_livestock")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[
                create_grazing_zones_layer,
                create_parcels_layer,
                create_conservancy_layer,
            ],
            grouped_layers=generate_livestock_layers,
            **(params.get("combine_custom_livestock") or {}),
        )
        .call()
    )

    draw_livestock_map = (
        task(draw_map_1)
        .validate()
        .set_task_instance_id("draw_livestock_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=combine_custom_livestock,
            view_state=gdf_image_extent,
            **(params.get("draw_livestock_map") or {}),
        )
        .call()
    )

    persist_livestock_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_livestock_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_livestock_map,
            filename="livestock_predation_events.html",
            filename_suffix=None,
            **(params.get("persist_livestock_urls") or {}),
        )
        .call()
    )

    livestock_predation_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("livestock_predation_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Livestock Predation Events Map",
            data=persist_livestock_urls,
            **(params.get("livestock_predation_map_widget") or {}),
        )
        .call()
    )

    convert_livestock_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("convert_livestock_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_livestock_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params.get("convert_livestock_png") or {}),
        )
        .call()
    )

    map_livestock_summary = (
        task(map_columns)
        .validate()
        .set_task_instance_id("map_livestock_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_livestock_predation,
            drop_columns=[],
            retain_columns=[
                "date",
                "Livestock Species",
                "Suspected Predator",
                "Total livestock affected",
            ],
            rename_columns={
                "Livestock Species": "livestock_species",
                "Suspected Predator": "suspected_predator",
                "Total livestock affected": "total_livestock_affected",
            },
            raise_if_not_found=False,
            **(params.get("map_livestock_summary") or {}),
        )
        .call()
    )

    replace_livestock_nulls = (
        task(fill_missing_values)
        .validate()
        .set_task_instance_id("replace_livestock_nulls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_livestock_summary,
            subset=["suspected_predator", "livestock_species"],
            value="Unknown",
            **(params.get("replace_livestock_nulls") or {}),
        )
        .call()
    )

    map_livestock_unknown = (
        task(replace_column_values)
        .validate()
        .set_task_instance_id("map_livestock_unknown")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=replace_livestock_nulls,
            columns=["suspected_predator"],
            value_map={"Other (specify in comments)": "Unknown"},
            inplace=True,
            errors="ignore",
            **(params.get("map_livestock_unknown") or {}),
        )
        .call()
    )

    convert_livestock_int = (
        task(convert_columns_to_int)
        .validate()
        .set_task_instance_id("convert_livestock_int")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_livestock_unknown,
            columns=["total_livestock_affected"],
            errors="coerce",
            fill_value=0,
            **(params.get("convert_livestock_int") or {}),
        )
        .call()
    )

    persist_livestock_summary = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_livestock_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            filename="livestock_predation_summary_table",
            df=convert_livestock_int,
            **(params.get("persist_livestock_summary") or {}),
        )
        .call()
    )

    map_illegal_grazing = (
        task(map_columns)
        .validate()
        .set_task_instance_id("map_illegal_grazing")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_illegal_prefix,
            drop_columns=[],
            retain_columns=[
                "date",
                "event_type",
                "geometry",
                "Herd Zone",
                "Landowner name",
                "action taken",
            ],
            rename_columns={},
            raise_if_not_found=False,
            **(params.get("map_illegal_grazing") or {}),
        )
        .call()
    )

    drop_null_grazing = (
        task(drop_null_geometry_1)
        .validate()
        .set_task_instance_id("drop_null_grazing")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=map_illegal_grazing,
            geometry_column="geometry",
            **(params.get("drop_null_grazing") or {}),
        )
        .call()
    )

    generate_illegal_layers = (
        task(create_scatterplot_layer_1)
        .validate()
        .set_task_instance_id("generate_illegal_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_fill_color": [0, 0, 128],
                "get_line_color": [0, 0, 128],
                "get_radius": 3,
                "opacity": 0.55,
                "stroked": True,
            },
            legend={
                "title": "Activity",
                "values": [{"label": "Illegal grazing", "color": "#000080"}],
                "sort": None,
                "label_suffix": None,
            },
            data_url=None,
            geodataframe=drop_null_grazing,
            **(params.get("generate_illegal_layers") or {}),
        )
        .call()
    )

    combine_custom_illegal = (
        task(combine_deckgl_map_layers)
        .validate()
        .set_task_instance_id("combine_custom_illegal")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[
                create_grazing_zones_layer,
                create_parcels_layer,
                create_conservancy_layer,
            ],
            grouped_layers=generate_illegal_layers,
            **(params.get("combine_custom_illegal") or {}),
        )
        .call()
    )

    draw_illegal_grazing = (
        task(draw_map_1)
        .validate()
        .set_task_instance_id("draw_illegal_grazing")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            geo_layers=combine_custom_illegal,
            view_state=gdf_image_extent,
            **(params.get("draw_illegal_grazing") or {}),
        )
        .call()
    )

    persist_illegal_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_illegal_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_illegal_grazing,
            filename="illegal_grazing_map.html",
            **(params.get("persist_illegal_urls") or {}),
        )
        .call()
    )

    illegal_grazing_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("illegal_grazing_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Illegal Grazing Events Map",
            data=persist_illegal_urls,
            **(params.get("illegal_grazing_map_widget") or {}),
        )
        .call()
    )

    convert_illegal_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("convert_illegal_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            html_path=persist_illegal_urls,
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params.get("convert_illegal_png") or {}),
        )
        .call()
    )

    mnc_events_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("mnc_events_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                mobile_boma_map_widget,
                livestock_predation_map_widget,
                illegal_grazing_map_widget,
                cattle_count_table_widget,
                predation_summary_table_widget,
            ],
            time_range=time_range,
            groupers=groupers,
            **(params.get("mnc_events_dashboard") or {}),
        )
        .call()
    )

    return mnc_events_dashboard
